/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.DAOusuarios;
import Model.Sessao;
import Model.Usuarios;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Colin
 */
public class AlterarSenha extends javax.swing.JInternalFrame {

    /**
     * Creates new form AlterarSenha
     */
    public AlterarSenha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPFatual = new javax.swing.JPasswordField();
        jPFnova = new javax.swing.JPasswordField();
        jPFconfirma = new javax.swing.JPasswordField();
        jBTconfirma = new javax.swing.JButton();
        jBTcancela = new javax.swing.JButton();

        setTitle("Alterar Senha");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Senha atual:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Nova Senha:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Confirmar Senha:");

        jPFatual.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jPFnova.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jPFconfirma.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jBTconfirma.setText("Confirma");
        jBTconfirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTconfirmaActionPerformed(evt);
            }
        });

        jBTcancela.setText("Cancela");
        jBTcancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTcancelaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBTconfirma)
                        .addGap(83, 83, 83)
                        .addComponent(jBTcancela))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPFatual, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPFnova, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPFconfirma, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jPFatual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPFnova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jPFconfirma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBTconfirma)
                    .addComponent(jBTcancela))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(410, 240));
    }// </editor-fold>//GEN-END:initComponents

    private void jBTconfirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTconfirmaActionPerformed
        Usuarios usersessao;
        usersessao = Sessao.getInstance().getUsersessao();
        
        DAOusuarios daouser = new DAOusuarios();
        Usuarios user;
        if(jPFatual.getText().isEmpty() || jPFnova.getText().isEmpty() || jPFconfirma.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Preencha todos os campos");
        }else{
            String pass = convertPasswordToMD5(jPFatual.getText());
            try{
            user = daouser.consultaUsuario(usersessao.getEmail(), pass);
            System.out.println("senha do user: "+user.getSenha());
            if(user.getSenha().equals(pass) ){
                System.out.println("Senhas iguais");
                int ret = -1;
                String newpass = convertPasswordToMD5(jPFnova.getText());
                System.out.println("new passord: "+newpass);
                ret = daouser.updatePassword(newpass, usersessao.getId());
                if(ret == 1){
                    JOptionPane.showMessageDialog(rootPane, "Senha alterada com sucesso!");
                    dispose();
                }else{
                    JOptionPane.showMessageDialog(rootPane, "Falha ao alterar a senha!");
                }
            }
            }
            catch(Exception e){
                    JOptionPane.showMessageDialog(rootPane, "Senha atual incorreta!");
                    }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jBTconfirmaActionPerformed

    private void jBTcancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTcancelaActionPerformed
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jBTcancelaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBTcancela;
    private javax.swing.JButton jBTconfirma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPFatual;
    private javax.swing.JPasswordField jPFconfirma;
    private javax.swing.JPasswordField jPFnova;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

public static String convertPasswordToMD5(String password) {
        String pass;
        MessageDigest md = null;
        try {
            md = MessageDigest.getInstance("MD5");
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
 
        BigInteger hash = new BigInteger(1, md.digest(password.getBytes()));
 
        pass = String.format("%32x", hash);
        
        System.out.println("Password Agora é : "+pass);
        return pass;
    }
}
