/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.DAOativos;
import DAO.DAOfornecedor;
import Model.Ativos;
import Model.Fornecedor;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Familia
 */
public class CadAtivos extends javax.swing.JFrame {
    DAOativos daoatv = new DAOativos();
    Ativos atv = new Ativos(); 
    
    /**
     * Creates new form CadAtivos
     */
    public CadAtivos() {
        initComponents();
        carregaAtivos();
        jTableativos.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jTableativos.setRowSorter(new TableRowSorter());
        jTableativos.setAutoCreateRowSorter(true);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTFid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jCBtipo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jTFdescricao = new javax.swing.JTextField();
        jTFmodelo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTFfabricante = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTFnumserie = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTFnf = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTFfornecedor = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jFTcnpj = new javax.swing.JFormattedTextField();
        jBTaddtipo = new javax.swing.JButton();
        jBTpesquisacnpj = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jBTeditar = new javax.swing.JButton();
        jBTnovo = new javax.swing.JButton();
        jBTsalvar = new javax.swing.JButton();
        jBTexcluir = new javax.swing.JButton();
        jBTcancelar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableativos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro de Ativos");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("ID:");

        jTFid.setEnabled(false);
        jTFid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFidActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Tipo");

        jCBtipo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCBtipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um Tipo" }));
        jCBtipo.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Descrição:");

        jTFdescricao.setEnabled(false);
        jTFdescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFdescricaoActionPerformed(evt);
            }
        });

        jTFmodelo.setEnabled(false);
        jTFmodelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFmodeloActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Modelo:");

        jTFfabricante.setEnabled(false);
        jTFfabricante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFfabricanteActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Fabricante:");

        jTFnumserie.setEnabled(false);
        jTFnumserie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFnumserieActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Número de Série:");

        jTFnf.setEnabled(false);
        jTFnf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFnfActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Nota Fiscal:");

        jTFfornecedor.setEnabled(false);
        jTFfornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFfornecedorActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Fornecedor:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("CNPJ Fornecedor:");

        try {
            jFTcnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTcnpj.setDragEnabled(true);
        jFTcnpj.setEnabled(false);
        jFTcnpj.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jBTaddtipo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jBTaddtipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/add.png"))); // NOI18N
        jBTaddtipo.setToolTipText("Adicionar Tipo");
        jBTaddtipo.setEnabled(false);
        jBTaddtipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTaddtipoActionPerformed(evt);
            }
        });

        jBTpesquisacnpj.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jBTpesquisacnpj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Search.png"))); // NOI18N
        jBTpesquisacnpj.setToolTipText("Consultar Fornecedor");
        jBTpesquisacnpj.setEnabled(false);
        jBTpesquisacnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTpesquisacnpjActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFfabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFnumserie, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jTFid, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jCBtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jBTaddtipo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jTFdescricao)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFnf, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jFTcnpj))
                                .addGap(18, 18, 18)
                                .addComponent(jBTpesquisacnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFfornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))))
                        .addGap(59, 59, 59))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCBtipo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel4)
                        .addGap(7, 7, 7)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBTaddtipo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFdescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7))
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFfabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFnumserie))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFnf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFfornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFTcnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBTpesquisacnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jBTeditar.setText("Editar");
        jBTeditar.setEnabled(false);
        jBTeditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTeditarActionPerformed(evt);
            }
        });

        jBTnovo.setText("Novo");
        jBTnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTnovoActionPerformed(evt);
            }
        });

        jBTsalvar.setText("Salvar");
        jBTsalvar.setEnabled(false);
        jBTsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTsalvarActionPerformed(evt);
            }
        });

        jBTexcluir.setText("Excluir");
        jBTexcluir.setEnabled(false);
        jBTexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTexcluirActionPerformed(evt);
            }
        });

        jBTcancelar.setText("Cancelar");
        jBTcancelar.setEnabled(false);
        jBTcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTcancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jBTnovo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jBTeditar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jBTsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jBTexcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jBTcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBTeditar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBTnovo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBTsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBTexcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBTcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTableativos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "TIPO", "DESCRIÇÃO", "MODELO", "FABRICANTE", "NÚM. DE SÉRIE", "NOTA FISCAL", "CNPJ FORNECEDOR", "FORNECEDOR", "LOCADO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableativos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableativosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableativos);
        if (jTableativos.getColumnModel().getColumnCount() > 0) {
            jTableativos.getColumnModel().getColumn(0).setMinWidth(30);
            jTableativos.getColumnModel().getColumn(0).setPreferredWidth(30);
            jTableativos.getColumnModel().getColumn(0).setMaxWidth(80);
            jTableativos.getColumnModel().getColumn(1).setMinWidth(100);
            jTableativos.getColumnModel().getColumn(2).setMinWidth(150);
            jTableativos.getColumnModel().getColumn(3).setMinWidth(100);
            jTableativos.getColumnModel().getColumn(4).setMinWidth(150);
            jTableativos.getColumnModel().getColumn(5).setMinWidth(100);
            jTableativos.getColumnModel().getColumn(6).setMinWidth(100);
            jTableativos.getColumnModel().getColumn(7).setMinWidth(150);
            jTableativos.getColumnModel().getColumn(8).setMinWidth(150);
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 668, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(319, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(702, 589));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTFidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFidActionPerformed

    private void jTFdescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFdescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFdescricaoActionPerformed

    private void jTFmodeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFmodeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFmodeloActionPerformed

    private void jTFfabricanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFfabricanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFfabricanteActionPerformed

    private void jTFnumserieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFnumserieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFnumserieActionPerformed

    private void jTFnfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFnfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFnfActionPerformed

    private void jTFfornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFfornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFfornecedorActionPerformed

    private void jTableativosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableativosMouseClicked
        if(jBTsalvar.isEnabled() == false){
            jTFid.setText(String.valueOf(jTableativos.getModel().getValueAt(jTableativos.getSelectedRow(), 0)));
            jCBtipo.setSelectedItem(jTableativos.getModel().getValueAt(jTableativos.getSelectedRow(), 1));
            jTFdescricao.setText((String) jTableativos.getModel().getValueAt(jTableativos.getSelectedRow(), 2));
            jTFmodelo.setText((String) jTableativos.getModel().getValueAt(jTableativos.getSelectedRow(), 3));
            jTFfabricante.setText((String) jTableativos.getModel().getValueAt(jTableativos.getSelectedRow(), 4));
            jTFnumserie.setText((String) jTableativos.getModel().getValueAt(jTableativos.getSelectedRow(), 5));
            jTFnf.setText((String) jTableativos.getModel().getValueAt(jTableativos.getSelectedRow(), 6));
            jFTcnpj.setText((String) jTableativos.getModel().getValueAt(jTableativos.getSelectedRow(), 7));
            jTFfornecedor.setText((String) jTableativos.getModel().getValueAt(jTableativos.getSelectedRow(), 8));
            jBTeditar.setEnabled(true);
            jBTcancelar.setEnabled(true);
            jBTnovo.setEnabled(false);
        }else{
            jTableativos.setEnabled(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableativosMouseClicked

    private void jBTcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTcancelarActionPerformed
        Cancelar(); clear();
        // TODO add your handling code here:
    }//GEN-LAST:event_jBTcancelarActionPerformed

    private void jBTexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTexcluirActionPerformed
        
        Cancelar(); clear();
        carregaAtivos();
        // TODO add your handling code here:
    }//GEN-LAST:event_jBTexcluirActionPerformed

    private void jBTsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTsalvarActionPerformed
        boolean ret = false;
        if(jTFid.getText().isEmpty()){
            /**Novo Ativo*/
            System.out.println("Novo Ativo -----------");
            DAOfornecedor daoforn = new DAOfornecedor();
            Fornecedor forn = new Fornecedor();
            forn = daoforn.consultaCNPJFornecedor(jFTcnpj.getText());
            
            atv = new Ativos();
            atv.setTipo((String) jCBtipo.getSelectedItem());
            atv.setDescricao(jTFdescricao.getText());
            atv.setModelo(jTFmodelo.getText());
            atv.setFabricante(jTFfabricante.getText());
            atv.setNum_serie(jTFnumserie.getText());
            atv.setNf(jTFnf.getText());
            atv.setFornecedor_for_id(forn.getId());
            atv.setFornecedor_for_cnpj(jFTcnpj.getText());

            ret = daoatv.adicionarAtivo(atv);
            if(ret){
                JOptionPane.showMessageDialog(null, "Ativo cadastrado com sucesso! ");
            }else{
                JOptionPane.showMessageDialog(null, "Falha na gravação do banco de dados! ");
            }
        }else{
            /**Atualização*/
            DAOfornecedor daoforn = new DAOfornecedor();
            Fornecedor forn = new Fornecedor();
            forn = daoforn.consultaCNPJFornecedor(jFTcnpj.getText());
            
            atv = new Ativos();
            atv.setId(Integer.parseInt(jTFid.getText()));
            atv.setTipo((String) jCBtipo.getSelectedItem());
            atv.setDescricao(jTFdescricao.getText());
            atv.setModelo(jTFmodelo.getText());
            atv.setFabricante(jTFfabricante.getText());
            atv.setNum_serie(jTFnumserie.getText());
            atv.setNf(jTFnf.getText());
            atv.setFornecedor_for_id(forn.getId());
            atv.setFornecedor_for_cnpj(forn.getCnpj());

            ret = daoatv.updateAtivo(atv);
            if(ret){
                JOptionPane.showMessageDialog(null, "Ativo atualizado com sucesso! ");
            }else{
                JOptionPane.showMessageDialog(null, "Falha atualização do banco de dados! ");
            }
        }
        Cancelar();clear();
        carregaAtivos();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jBTsalvarActionPerformed

    private void jBTeditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTeditarActionPerformed
        Editar();
        jBTexcluir.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jBTeditarActionPerformed

    private void jBTnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTnovoActionPerformed
        Editar();
        // TODO add your handling code here:
    }//GEN-LAST:event_jBTnovoActionPerformed

    private void jBTaddtipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTaddtipoActionPerformed
        String ret = JOptionPane.showInputDialog("Informe o nome do novo tipo: ");
        System.out.println("Valor do cancelar é : "+ret);
        if(ret != null && !"".equals(ret)){
            jCBtipo.addItem(ret);
            jCBtipo.setSelectedItem(ret);
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jBTaddtipoActionPerformed

    private void jBTpesquisacnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTpesquisacnpjActionPerformed
        
        if(jFTcnpj.getText().length()< 18){
            JOptionPane.showMessageDialog(rootPane, "CNPJ inválido! confira o valor digitado e tente novamente.");
        }else{
            try {
                DAOfornecedor daoforn = new DAOfornecedor();
                Fornecedor forn = new Fornecedor();
                forn = daoforn.consultaCNPJFornecedor(jFTcnpj.getText());
                String nome = forn.getNome();
                if(forn.getNome() == null){
                    JOptionPane.showMessageDialog(null, "Fornecedor não cadastrado!"+nome);
                }else{
                    jTFfornecedor.setText(forn.getNome());
                    JOptionPane.showMessageDialog(null, "Fornecedor encontrado!");
                }
            } catch (Exception e) {
                System.out.println("Erro ao consultar Fornecedor. "+e);
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jBTpesquisacnpjActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadAtivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadAtivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadAtivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadAtivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadAtivos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBTaddtipo;
    private javax.swing.JButton jBTcancelar;
    private javax.swing.JButton jBTeditar;
    private javax.swing.JButton jBTexcluir;
    private javax.swing.JButton jBTnovo;
    private javax.swing.JButton jBTpesquisacnpj;
    private javax.swing.JButton jBTsalvar;
    private javax.swing.JComboBox<String> jCBtipo;
    private javax.swing.JFormattedTextField jFTcnpj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFdescricao;
    private javax.swing.JTextField jTFfabricante;
    private javax.swing.JTextField jTFfornecedor;
    private javax.swing.JTextField jTFid;
    private javax.swing.JTextField jTFmodelo;
    private javax.swing.JTextField jTFnf;
    private javax.swing.JTextField jTFnumserie;
    private javax.swing.JTable jTableativos;
    // End of variables declaration//GEN-END:variables

    public void carregaAtivos(){
        List<Ativos> listaatv = new ArrayList();
        listaatv = daoatv.listaAtivos();

        DefaultTableModel model = (DefaultTableModel) jTableativos.getModel();
        model.setNumRows(0);
        
        for(int i= 0; i<listaatv.size() ; i++){
            atv = new Ativos(); 
            atv = listaatv.get(i); 
            String loc = "";
            System.out.println("Locacao_ativos_loc_id");
            if (atv.getLocacao_ativos_loc_id() != 0){
                loc = "Sim";
            }else{
                loc = "Não";
            }
            
            model.addRow(new Object[]{atv.getId(), atv.getTipo(), atv.getDescricao(), 
                                      atv.getModelo(), atv.getFabricante(), atv.getNum_serie(), atv.getNf(), 
                                      atv.getCnpjforn(), atv.getFornecedor(), loc});
        }
        Ativos tipo;
        tipo = new Ativos();
        List<Ativos> listatipo = new ArrayList();
        listatipo = daoatv.listaTipos();
        jCBtipo.removeAllItems();
        for(int i=0; i < listatipo.size(); i++){
            //System.out.println("Tamanho da lista "+i);
            tipo = new Ativos();
            tipo = listatipo.get(i);
            System.out.println("Tipo = "+tipo.getTipo());
            jCBtipo.addItem(tipo.getTipo());
        }
    }

    public void clear(){
        jTFid.setText(null);
        jCBtipo.setSelectedIndex(0);
        jTFdescricao.setText(null);
        jTFmodelo.setText(null);
        jTFfabricante.setText(null);
        jTFnumserie.setText(null);
        jTFnf.setText(null);
        jFTcnpj.setText(null);
        jTFfornecedor.setText(null);
    }
    
    public void Cancelar(){
        jTFid.setEnabled(false);
        jCBtipo.setEnabled(false);
        jTFdescricao.setEnabled(false);
        jTFmodelo.setEnabled(false);
        jTFfabricante.setEnabled(false);
        jTFnumserie.setEnabled(false);
        jTFnf.setEnabled(false);
        jFTcnpj.setEnabled(false);
        
        jBTaddtipo.setEnabled(false);
        jBTpesquisacnpj.setEnabled(false);
        jBTnovo.setEnabled(true);
        jBTeditar.setEnabled(false);
        jBTsalvar.setEnabled(false);
        jBTexcluir.setEnabled(false);
        jBTcancelar.setEnabled(false);
        jTableativos.setEnabled(true);
    }
    
    public void Editar(){
        jTFid.setEnabled(false);
        jCBtipo.setEnabled(true);
        jTFdescricao.setEnabled(true);
        jTFmodelo.setEnabled(true);
        jTFfabricante.setEnabled(true);
        jTFnumserie.setEnabled(true);
        jTFnf.setEnabled(true);
        jFTcnpj.setEnabled(true);
        
        jBTaddtipo.setEnabled(true);
        jBTpesquisacnpj.setEnabled(true);
        jBTnovo.setEnabled(false);
        jBTeditar.setEnabled(false);
        jBTsalvar.setEnabled(true);
        jBTexcluir.setEnabled(true);
        jBTcancelar.setEnabled(true);
        jTableativos.setEnabled(false);
    }
}
