/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.DAOdepartamento;
import DAO.DAOusuarios;
import Model.Departamento;
import Model.Usuarios;
import java.awt.event.ItemEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Colin
 */
public class CadDepartamento extends javax.swing.JFrame {

    /**
     * Creates new form CadDepartamento
     */
    public CadDepartamento() {
        initComponents();
        carregaDepartamento();
        carregarResponavel();
        
        jTabledepartamento.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        
        /** habilita a ordenação por colunas */
        jTabledepartamento.setRowSorter(new TableRowSorter());
        jTabledepartamento.setAutoCreateRowSorter(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTFid = new javax.swing.JTextField();
        jTFdepartamento = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jCBemailresp = new javax.swing.JComboBox<>();
        jCBnomeresp = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jBTnovo = new javax.swing.JButton();
        jBTeditar = new javax.swing.JButton();
        jBTsalvar = new javax.swing.JButton();
        jBTexcluir = new javax.swing.JButton();
        jBTcancelar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTabledepartamento = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Departamento");
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 400));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setPreferredSize(new java.awt.Dimension(480, 100));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("ID:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Nome do Departamento:");

        jTFid.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTFid.setEnabled(false);

        jTFdepartamento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTFdepartamento.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cadastro de Departamento");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(224, 224, 224)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTFdepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(jTFid, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFdepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Responsável"));
        jPanel3.setToolTipText("");
        jPanel3.setPreferredSize(new java.awt.Dimension(477, 88));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Nome:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("E-mail:");

        jCBemailresp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "E-mail do responsável" }));
        jCBemailresp.setEnabled(false);
        jCBemailresp.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBemailrespItemStateChanged(evt);
            }
        });

        jCBnomeresp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o Responsável" }));
        jCBnomeresp.setEnabled(false);
        jCBnomeresp.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBnomerespItemStateChanged(evt);
            }
        });
        jCBnomeresp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBnomerespActionPerformed(evt);
            }
        });
        jCBnomeresp.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                jCBnomerespCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jCBnomeresp, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(145, 145, 145))
                    .addComponent(jCBemailresp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCBnomeresp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCBemailresp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jBTnovo.setText("Novo");
        jBTnovo.setMargin(new java.awt.Insets(2, 5, 2, 5));
        jBTnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTnovoActionPerformed(evt);
            }
        });

        jBTeditar.setText("Editar");
        jBTeditar.setEnabled(false);
        jBTeditar.setMargin(new java.awt.Insets(2, 5, 2, 5));
        jBTeditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTeditarActionPerformed(evt);
            }
        });

        jBTsalvar.setText("Salvar");
        jBTsalvar.setEnabled(false);
        jBTsalvar.setMargin(new java.awt.Insets(2, 5, 2, 5));
        jBTsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTsalvarActionPerformed(evt);
            }
        });

        jBTexcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cancel.png"))); // NOI18N
        jBTexcluir.setText("Excluir");
        jBTexcluir.setEnabled(false);
        jBTexcluir.setMargin(new java.awt.Insets(2, 5, 2, 5));
        jBTexcluir.setPreferredSize(new java.awt.Dimension(92, 30));
        jBTexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTexcluirActionPerformed(evt);
            }
        });

        jBTcancelar.setText("Cancelar");
        jBTcancelar.setEnabled(false);
        jBTcancelar.setMargin(new java.awt.Insets(2, 5, 2, 5));
        jBTcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTcancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jBTnovo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBTeditar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBTsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBTexcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBTcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBTnovo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBTeditar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBTsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBTexcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBTcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTabledepartamento.setBackground(new java.awt.Color(204, 204, 204));
        jTabledepartamento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTabledepartamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Departamento", "Nome do Responsável", "E-mail"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTabledepartamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabledepartamentoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTabledepartamento);
        if (jTabledepartamento.getColumnModel().getColumnCount() > 0) {
            jTabledepartamento.getColumnModel().getColumn(0).setMinWidth(30);
            jTabledepartamento.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTabledepartamento.getColumnModel().getColumn(0).setMaxWidth(80);
            jTabledepartamento.getColumnModel().getColumn(1).setMinWidth(145);
            jTabledepartamento.getColumnModel().getColumn(1).setPreferredWidth(145);
            jTabledepartamento.getColumnModel().getColumn(1).setMaxWidth(500);
            jTabledepartamento.getColumnModel().getColumn(2).setMinWidth(150);
            jTabledepartamento.getColumnModel().getColumn(2).setPreferredWidth(150);
            jTabledepartamento.getColumnModel().getColumn(2).setMaxWidth(500);
            jTabledepartamento.getColumnModel().getColumn(3).setMinWidth(150);
            jTabledepartamento.getColumnModel().getColumn(3).setPreferredWidth(150);
            jTabledepartamento.getColumnModel().getColumn(3).setMaxWidth(500);
        }

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 479, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 148, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(15, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(521, 506));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBTexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTexcluirActionPerformed
        int retorno = JOptionPane.showConfirmDialog(null, "Confirma a exclusão do departamento? ", "Confirmação", JOptionPane.YES_NO_OPTION);
        if(retorno == JOptionPane.YES_OPTION){
            DAOdepartamento daodepto = new DAOdepartamento(); 
            daodepto.exluirDepartamento(Integer.parseInt(jTFid.getText()));
            JOptionPane.showMessageDialog(this, "Departamento Excluido com Sucesso!");
            carregaDepartamento();
            carregarResponavel();
            cancelar();
            clear();
        }else{
            JOptionPane.showMessageDialog(this, "Ação cancelada!");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jBTexcluirActionPerformed

    private void jTabledepartamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabledepartamentoMouseClicked
        
        jBTeditar.setEnabled(true);
        jBTcancelar.setEnabled(true);
        jBTnovo.setEnabled(false);
        
        int ra;
        ra = (int) jTabledepartamento.getModel().getValueAt(jTabledepartamento.getSelectedRow(), 0);
        jTFid.setText(String.valueOf(jTabledepartamento.getModel().getValueAt(jTabledepartamento.getSelectedRow(), 0)));
        jTFdepartamento.setText((String) jTabledepartamento.getModel().getValueAt(jTabledepartamento.getSelectedRow(), 1));
        //jTFnomeresp.setText((String) jTabledepartamento.getModel().getValueAt(jTabledepartamento.getSelectedRow(), 2));
        //jTFnomeresp.setText((String) jTabledepartamento.getModel().getValueAt(jTabledepartamento.getSelectedRow(), 2));
        //jTFemailresp.setText((String) jTabledepartamento.getModel().getValueAt(jTabledepartamento.getSelectedRow(), 3));
        jCBemailresp.setSelectedItem(jTabledepartamento.getModel().getValueAt(jTabledepartamento.getSelectedRow(), 3));
        
        

        // TODO add your handling code here:
    }//GEN-LAST:event_jTabledepartamentoMouseClicked

    private void jBTeditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTeditarActionPerformed
        editar();
        jBTeditar.setEnabled(false);
        jBTcancelar.setEnabled(true);
        jBTnovo.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jBTeditarActionPerformed

    private void jBTcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTcancelarActionPerformed
        cancelar();
        clear();
        // TODO add your handling code here:
    }//GEN-LAST:event_jBTcancelarActionPerformed

    private void jBTnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTnovoActionPerformed
        editar();
        // TODO add your handling code here:
    }//GEN-LAST:event_jBTnovoActionPerformed

    private void jBTsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTsalvarActionPerformed
        
        if(jCBnomeresp.getSelectedItem().toString().contains("Selecione o Responsável")){
            JOptionPane.showMessageDialog(null, "Selecione um responsável pelo departamento!");
        }else{
            DAOdepartamento daodep = new DAOdepartamento();
            Departamento dep = new Departamento();
            // Consulta email do usuário e pega o id
            DAOusuarios daousu = new DAOusuarios();
            String nome = (String) jCBemailresp.getSelectedItem();
            Usuarios usu = new Usuarios();
            usu = daousu.consultaUsuario(nome);  

            dep.setNome(jTFdepartamento.getText());
            dep.setUsuarios_usu_id(usu.getId());

            if(jTFid.getText().isEmpty()){
                daodep.inserirDepartamento(dep);    
            }else{
                dep.setId(Integer.parseInt(jTFid.getText()));
                daodep.updateDepartamento(dep);
            }     

            cancelar();
            carregaDepartamento();
            carregarResponavel();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jBTsalvarActionPerformed

    private void jCBnomerespItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBnomerespItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED){
            if(this.jCBnomeresp.getSelectedIndex()>0){
                jCBemailresp.setSelectedIndex(jCBnomeresp.getSelectedIndex());
            }
            else{
                jCBemailresp.setSelectedIndex(0);
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBnomerespItemStateChanged

    private void jCBnomerespCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jCBnomerespCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBnomerespCaretPositionChanged

    private void jCBnomerespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBnomerespActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jCBnomerespActionPerformed

    private void jCBemailrespItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBemailrespItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED){
            if(this.jCBemailresp.getSelectedIndex()>0){
                jCBnomeresp.setSelectedIndex(jCBemailresp.getSelectedIndex());
            }
            else{
                jCBnomeresp.setSelectedIndex(0);
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBemailrespItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadDepartamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBTcancelar;
    private javax.swing.JButton jBTeditar;
    private javax.swing.JButton jBTexcluir;
    private javax.swing.JButton jBTnovo;
    private javax.swing.JButton jBTsalvar;
    private javax.swing.JComboBox<String> jCBemailresp;
    private javax.swing.JComboBox<String> jCBnomeresp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTFdepartamento;
    private javax.swing.JTextField jTFid;
    private javax.swing.JTable jTabledepartamento;
    // End of variables declaration//GEN-END:variables

public void carregaDepartamento(){
        /**  Carrega jTableDepartamento*/
        
        DAOdepartamento daodepto = new DAOdepartamento();
        Departamento depto;
        List<Departamento> listadepto; 
        listadepto = daodepto.listaDepartamento();
        
        DefaultTableModel model = (DefaultTableModel) jTabledepartamento.getModel();
        model.setNumRows(0);
        
        jTabledepartamento.getColumnModel().getColumn(0).setPreferredWidth(5);
        jTabledepartamento.getColumnModel().getColumn(1).setPreferredWidth(50);
        jTabledepartamento.getColumnModel().getColumn(2).setPreferredWidth(50);
        jTabledepartamento.getColumnModel().getColumn(3).setPreferredWidth(50);
        
        for(int i = 0; i<listadepto.size(); i++){
           depto = listadepto.get(i);
           model.addRow(new Object[] {depto.getId(), depto.getNome(), depto.getNomeresp(), depto.getEmailresp()});
           
        }
    }    

public void carregarResponavel(){
        /**  Carrega ComboBox Nome e email do responsavel*/
        
        DAOusuarios daousu = new DAOusuarios();
        Usuarios usu = new Usuarios();
        List<Usuarios> listauser; 
        listauser = daousu.listaUsuarios();
 
        for(int i = 0; i<listauser.size(); i++){
           usu = listauser.get(i);
           jCBnomeresp.addItem(usu.getNome());
           jCBemailresp.addItem(usu.getEmail());
           
        }
    }
    
public void editar(){
        jTFid.setEnabled(false);
        jTFdepartamento.setEnabled(true);
        //jTFnomeresp.setEnabled(true);
        //jTFemailresp.setEnabled(true);
        jCBnomeresp.setEnabled(true);
        jCBemailresp.setEnabled(true);
        jBTsalvar.setEnabled(true);
        jBTcancelar.setEnabled(true);
        jBTexcluir.setEnabled(true);
        jBTnovo.setEnabled(false);
        jBTeditar.setEnabled(false);
        jTabledepartamento.setEnabled(false);
        
    }
    
    public void cancelar(){
        jTFid.setEnabled(false);
        jTFdepartamento.setEnabled(false);
        //jTFnomeresp.setEnabled(false);
        //jTFemailresp.setEnabled(false);
        jCBnomeresp.setEnabled(false);
        jCBemailresp.setEnabled(false);
        jBTsalvar.setEnabled(false);
        jBTcancelar.setEnabled(false);
        jBTexcluir.setEnabled(false);
        jBTeditar.setEnabled(false);
        jBTnovo.setEnabled(true);
        jTabledepartamento.setEnabled(true);
        
    }
    
    public void clear(){
        jTFid.setText(null);
        jTFdepartamento.setText(null);
        jCBnomeresp.setSelectedItem(0);
        jCBemailresp.setSelectedIndex(0);
    }

}
