/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.DAOfornecedor;
import Model.Fornecedor;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author STA-Administrador
 */
public class CadFornecedor extends javax.swing.JFrame {

    /**
     * Creates new form CadFornecedor
     */
    DAOfornecedor daoforn = new DAOfornecedor();
    Fornecedor forn;
    boolean atualizacao = false;

    public CadFornecedor() {
        initComponents();
        carregaFornecedor();
        jTablefornecedor.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        
        /** habilita a ordenação por colunas */
        jTablefornecedor.setRowSorter(new TableRowSorter());
        jTablefornecedor.setAutoCreateRowSorter(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jPanelinfobasica = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTFnome = new javax.swing.JTextField();
        jTFcontato = new javax.swing.JTextField();
        jTFemail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jFTcnpj = new javax.swing.JFormattedTextField();
        jFTtelefone = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        jTFid = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTFendereco = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTFbairro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTFcidade = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTFestado = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jFTcep = new javax.swing.JFormattedTextField();
        jTFnumero = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jBTnovo = new javax.swing.JButton();
        jBTeditar = new javax.swing.JButton();
        jBTsalvar = new javax.swing.JButton();
        jBTexcluir = new javax.swing.JButton();
        jBTcancelar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablefornecedor = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Fornecedores");
        setPreferredSize(new java.awt.Dimension(750, 550));
        setResizable(false);

        jScrollPane2.setBorder(null);
        jScrollPane2.setAutoscrolls(true);

        jPanel5.setPreferredSize(new java.awt.Dimension(750, 713));

        jPanelinfobasica.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelinfobasica.setPreferredSize(new java.awt.Dimension(600, 317));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro de Fornecedores");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("CNPJ:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Nome:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("E-mail:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Contato:");

        jTFnome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTFnome.setEnabled(false);

        jTFcontato.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTFcontato.setEnabled(false);

        jTFemail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTFemail.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Telefone:");

        try {
            jFTcnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTcnpj.setEnabled(false);
        jFTcnpj.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        try {
            jFTtelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTtelefone.setEnabled(false);
        jFTtelefone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("ID:");

        jTFid.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTFid.setEnabled(false);

        javax.swing.GroupLayout jPanelinfobasicaLayout = new javax.swing.GroupLayout(jPanelinfobasica);
        jPanelinfobasica.setLayout(jPanelinfobasicaLayout);
        jPanelinfobasicaLayout.setHorizontalGroup(
            jPanelinfobasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelinfobasicaLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanelinfobasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelinfobasicaLayout.createSequentialGroup()
                        .addGroup(jPanelinfobasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelinfobasicaLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanelinfobasicaLayout.createSequentialGroup()
                                .addComponent(jTFcontato)
                                .addGap(27, 27, 27)))
                        .addGroup(jPanelinfobasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jTFemail, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addGroup(jPanelinfobasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jFTtelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelinfobasicaLayout.createSequentialGroup()
                        .addGroup(jPanelinfobasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jTFid, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(jPanelinfobasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jFTcnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addGroup(jPanelinfobasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelinfobasicaLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(320, 320, 320))
                            .addComponent(jTFnome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(50, 50, 50))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelinfobasicaLayout.setVerticalGroup(
            jPanelinfobasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelinfobasicaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanelinfobasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelinfobasicaLayout.createSequentialGroup()
                        .addGroup(jPanelinfobasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelinfobasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFTcnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelinfobasicaLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanelinfobasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelinfobasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelinfobasicaLayout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTFemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelinfobasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jFTtelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelinfobasicaLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(27, 27, 27))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelinfobasicaLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFcontato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setPreferredSize(new java.awt.Dimension(600, 125));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Endereço:");

        jTFendereco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTFendereco.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Bairro:");

        jTFbairro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTFbairro.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Cidade:");

        jTFcidade.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTFcidade.setEnabled(false);
        jTFcidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFcidadeActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Estado:");

        jTFestado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTFestado.setEnabled(false);
        jTFestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFestadoActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("CEP:");

        jFTcep.setColumns(15);
        try {
            jFTcep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTcep.setEnabled(false);
        jFTcep.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jFTcep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFTcepActionPerformed(evt);
            }
        });

        jTFnumero.setColumns(5);
        jTFnumero.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTFnumero.setEnabled(false);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Número:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFcidade, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jTFestado, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTFnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9)))
                        .addGap(61, 61, 61)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jFTcep, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jTFendereco, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFbairro, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(30, 30, 30))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFnumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFbairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFendereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTFestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTFcidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFTcep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jPanel4.setPreferredSize(new java.awt.Dimension(600, 100));

        jBTnovo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jBTnovo.setText("Novo");
        jBTnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTnovoActionPerformed(evt);
            }
        });

        jBTeditar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jBTeditar.setText("Editar");
        jBTeditar.setEnabled(false);
        jBTeditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTeditarActionPerformed(evt);
            }
        });

        jBTsalvar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jBTsalvar.setText("Salvar");
        jBTsalvar.setEnabled(false);
        jBTsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTsalvarActionPerformed(evt);
            }
        });

        jBTexcluir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jBTexcluir.setText("Excluir");
        jBTexcluir.setEnabled(false);
        jBTexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTexcluirActionPerformed(evt);
            }
        });

        jBTcancelar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jBTcancelar.setText("Cancelar");
        jBTcancelar.setEnabled(false);
        jBTcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTcancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jBTnovo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jBTeditar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jBTsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jBTexcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jBTcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBTnovo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBTeditar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBTsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBTexcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBTcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Lista de Fornecedores"));
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 204));

        jTablefornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "CNPJ", "NOME", "ENDEREÇO", "NÚMERO", "TELEFONE", "E-MAIL", "CONTATO", "BAIRRO", "CIDADE", "ESTADO", "CEP"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablefornecedor.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTablefornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablefornecedorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablefornecedor);
        if (jTablefornecedor.getColumnModel().getColumnCount() > 0) {
            jTablefornecedor.getColumnModel().getColumn(0).setMinWidth(30);
            jTablefornecedor.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTablefornecedor.getColumnModel().getColumn(0).setMaxWidth(80);
            jTablefornecedor.getColumnModel().getColumn(1).setMinWidth(150);
            jTablefornecedor.getColumnModel().getColumn(2).setMinWidth(200);
            jTablefornecedor.getColumnModel().getColumn(3).setMinWidth(100);
            jTablefornecedor.getColumnModel().getColumn(4).setMinWidth(80);
            jTablefornecedor.getColumnModel().getColumn(5).setMinWidth(150);
            jTablefornecedor.getColumnModel().getColumn(6).setMinWidth(100);
            jTablefornecedor.getColumnModel().getColumn(7).setMinWidth(100);
            jTablefornecedor.getColumnModel().getColumn(8).setMinWidth(80);
            jTablefornecedor.getColumnModel().getColumn(9).setMinWidth(100);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE)
                        .addComponent(jPanelinfobasica, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelinfobasica, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(776, 589));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTFcidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFcidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFcidadeActionPerformed

    private void jTFestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFestadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFestadoActionPerformed

    private void jBTsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTsalvarActionPerformed
        System.out.println("Atualização é = "+atualizacao);
        boolean ret;
        if (atualizacao) {
            
            if (jFTcnpj.getText().isEmpty() || jTFnome.getText().isEmpty()
                || jTFcontato.getText().isEmpty() || jTFemail.getText().isEmpty()
                || jFTtelefone.getText().isEmpty() || jTFendereco.getText().isEmpty()|| jTFnumero.getText().isEmpty()
                || jTFbairro.getText().isEmpty() || jTFcidade.getText().isEmpty()
                || jTFestado.getText().isEmpty() || jFTcep.getText().isEmpty()) {
                
                JOptionPane.showMessageDialog(null, "Todos os dados são de preenchimento obrigatório!");

            } else{
                
                /**
                 * cria um novo fornecedor
                 */
                forn = new Fornecedor();
                /**
                 * seta os valores do novo fornecedor
                 */
                forn.setId(Integer.parseInt(jTFid.getText()));
                forn.setCnpj(jFTcnpj.getText());
                forn.setNome(jTFnome.getText());
                forn.setContato(jTFcontato.getText());
                forn.setEmail(jTFemail.getText());
                forn.setTelefone(jFTtelefone.getText());
                forn.setEndereco(jTFendereco.getText());
                forn.setNumero(jTFnumero.getText());
                forn.setBairro(jTFbairro.getText());
                forn.setCidade(jTFcidade.getText());
                forn.setEstado(jTFestado.getText());
                forn.setCep(jFTcep.getText());

                ret = daoforn.updateFornecedor(forn);
                carregaFornecedor();
                if(ret){
                    JOptionPane.showMessageDialog(null, "Fornecedor atualizado com sucesso!");
                }else{
                    JOptionPane.showMessageDialog(null, "Falha na atualização!");
                }
                
            }
            
        } else if (jFTcnpj.getText().isEmpty() || jTFnome.getText().isEmpty()
                || jTFcontato.getText().isEmpty() || jTFemail.getText().isEmpty()
                || jFTtelefone.getText().isEmpty() || jTFendereco.getText().isEmpty()|| jTFnumero.getText().isEmpty()
                || jTFbairro.getText().isEmpty() || jTFcidade.getText().isEmpty()
                || jTFestado.getText().isEmpty() || jFTcep.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Todos os dados são de preenchimento obrigatório!");

        } else {
            /**
             * cria um novo fornecedor 
             */
            forn = new Fornecedor();
            
            /** seta os valores do novo fornecedor*/
            forn.setCnpj(jFTcnpj.getText());
            forn.setNome(jTFnome.getText());
            forn.setContato(jTFcontato.getText());
            forn.setEmail(jTFemail.getText());
            forn.setTelefone(jFTtelefone.getText());
            forn.setEndereco(jTFendereco.getText());
            forn.setNumero(jTFendereco.getText());
            forn.setBairro(jTFbairro.getText());
            forn.setCidade(jTFcidade.getText());
            forn.setEstado(jTFestado.getText());
            forn.setCep(jFTcep.getText());

            ret = daoforn.adicionarFornecedor(forn);
            
            if(ret){
                    JOptionPane.showMessageDialog(null, "Fornecedor cadastrado com sucesso!");
                }else{
                    JOptionPane.showMessageDialog(null, "Falha ao gravar no Banco de dados!");
                }
            
            System.out.println("CNPJ = " + jFTcnpj.getText());
        }
        cancelar(); clear();
        carregaFornecedor();
                
        // TODO add your handling code here:
    }//GEN-LAST:event_jBTsalvarActionPerformed

    private void jBTnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTnovoActionPerformed
        clear();
        editar();
        atualizacao = false;
        jBTexcluir.setEnabled(false);
        jTablefornecedor.setEnabled(false);
        System.out.println("Atualização é = "+atualizacao);
                
        // TODO add your handling code here:
    }//GEN-LAST:event_jBTnovoActionPerformed

    private void jFTcepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFTcepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTcepActionPerformed

    private void jTablefornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablefornecedorMouseClicked
        System.out.println("carrega valores");
        if(jBTsalvar.isEnabled()== false){
            /**
             * Popula os campos com o valor da linha selecioanada na tabela
             */
            jTFid.setText(String.valueOf(jTablefornecedor.getModel().getValueAt(jTablefornecedor.getSelectedRow(), 0)));
            jFTcnpj.setText((String) jTablefornecedor.getModel().getValueAt(jTablefornecedor.getSelectedRow(), 1));
            jTFnome.setText((String) jTablefornecedor.getModel().getValueAt(jTablefornecedor.getSelectedRow(), 2));
            jTFendereco.setText((String) jTablefornecedor.getModel().getValueAt(jTablefornecedor.getSelectedRow(), 3));
            jTFnumero.setText((String) jTablefornecedor.getModel().getValueAt(jTablefornecedor.getSelectedRow(), 4));
            jFTtelefone.setText((String) jTablefornecedor.getModel().getValueAt(jTablefornecedor.getSelectedRow(), 5));
            jTFemail.setText((String) jTablefornecedor.getModel().getValueAt(jTablefornecedor.getSelectedRow(), 6));
            jTFcontato.setText((String) jTablefornecedor.getModel().getValueAt(jTablefornecedor.getSelectedRow(), 7));
            jTFbairro.setText((String) jTablefornecedor.getModel().getValueAt(jTablefornecedor.getSelectedRow(), 8));
            jTFcidade.setText((String) jTablefornecedor.getModel().getValueAt(jTablefornecedor.getSelectedRow(), 9));
            jTFestado.setText((String) jTablefornecedor.getModel().getValueAt(jTablefornecedor.getSelectedRow(), 10));
            jFTcep.setText((String) jTablefornecedor.getModel().getValueAt(jTablefornecedor.getSelectedRow(), 11));
            
            enableselect();
        }else{
            jTablefornecedor.setEnabled(false);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jTablefornecedorMouseClicked

    private void jBTeditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTeditarActionPerformed
        editar();
        atualizacao = true;

        // TODO add your handling code here:
    }//GEN-LAST:event_jBTeditarActionPerformed

    private void jBTexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTexcluirActionPerformed
        String msg = "Tem certeza que deseja excluir o Fornecedor: \n"+"CNPJ: "+jFTcnpj.getText()+"\nNome: "+jTFnome.getText()+" ?";
        int result = JOptionPane.showConfirmDialog(null, msg, "Confirmação de Exclusão", JOptionPane.YES_NO_OPTION);
        if(result == JOptionPane.YES_OPTION){
            daoforn.deleteFornecedor((String) jFTcnpj.getText());
            JOptionPane.showMessageDialog(null, "Fornecedor excluido com sucesso!");
        }else{
            JOptionPane.showMessageDialog(null, "Ação cancelada!");
        }
        cancelar(); clear();
        // TODO add your handling code here:
    }//GEN-LAST:event_jBTexcluirActionPerformed

    private void jBTcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTcancelarActionPerformed
        cancelar(); clear();
        System.out.println("Atualização é = "+atualizacao);
        // TODO add your handling code here:
    }//GEN-LAST:event_jBTcancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadFornecedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBTcancelar;
    private javax.swing.JButton jBTeditar;
    private javax.swing.JButton jBTexcluir;
    private javax.swing.JButton jBTnovo;
    private javax.swing.JButton jBTsalvar;
    private javax.swing.JFormattedTextField jFTcep;
    private javax.swing.JFormattedTextField jFTcnpj;
    private javax.swing.JFormattedTextField jFTtelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelinfobasica;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTFbairro;
    private javax.swing.JTextField jTFcidade;
    private javax.swing.JTextField jTFcontato;
    private javax.swing.JTextField jTFemail;
    private javax.swing.JTextField jTFendereco;
    private javax.swing.JTextField jTFestado;
    private javax.swing.JTextField jTFid;
    private javax.swing.JTextField jTFnome;
    private javax.swing.JTextField jTFnumero;
    private javax.swing.JTable jTablefornecedor;
    // End of variables declaration//GEN-END:variables

    public void carregaFornecedor() {

        List<Fornecedor> listforn = new ArrayList();
        listforn = daoforn.listaFornecedor();

        DefaultTableModel model = (DefaultTableModel) jTablefornecedor.getModel();
        model.setNumRows(0);

        for (int i = 0; i < listforn.size(); i++) {
            forn = listforn.get(i);
            model.addRow(new Object[]{forn.getId(), forn.getCnpj(), forn.getNome(), forn.getEndereco(),forn.getNumero(),
                forn.getTelefone(), forn.getEmail(), forn.getContato(), forn.getBairro(), forn.getCidade(), forn.getEstado(), forn.getCep()});

        }

    }

    public void enableselect(){
        jBTeditar.setEnabled(true);
        jBTcancelar.setEnabled(true);
        jBTnovo.setEnabled(false);
        jTablefornecedor.setEnabled(true);
    }
    
    public void editar() {
        jFTcnpj.setEnabled(true);
        jTFnome.setEnabled(true);
        jTFcontato.setEnabled(true);
        jTFemail.setEnabled(true);
        jFTtelefone.setEnabled(true);
        jTFendereco.setEnabled(true);
        jTFnumero.setEnabled(true);
        jTFbairro.setEnabled(true);
        jTFcidade.setEnabled(true);
        jTFestado.setEnabled(true);
        jFTcep.setEnabled(true);
        //botões
        jBTnovo.setEnabled(false);
        jBTeditar.setEnabled(false);
        jBTsalvar.setEnabled(true);
        jBTexcluir.setEnabled(true);
        jBTcancelar.setEnabled(true);

        atualizacao = true;

    }

    public void cancelar() {
        jFTcnpj.setEnabled(false);
        jTFnome.setEnabled(false);
        jTFcontato.setEnabled(false);
        jTFemail.setEnabled(false);
        jFTtelefone.setEnabled(false);
        jTFendereco.setEnabled(false);
        jTFnumero.setEnabled(false);
        jTFbairro.setEnabled(false);
        jTFcidade.setEnabled(false);
        jTFestado.setEnabled(false);
        jFTcep.setEnabled(false);
        //botões
        jBTnovo.setEnabled(true);
        jBTeditar.setEnabled(false);
        jBTsalvar.setEnabled(false);
        jBTexcluir.setEnabled(false);
        jBTcancelar.setEnabled(false);

        jTablefornecedor.setEnabled(true);
        atualizacao = true;
    }

    public void clear() {
        jTFid.setText(null);
        jFTcnpj.setText(null);
        jTFnome.setText(null);
        jTFcontato.setText(null);
        jTFemail.setText(null);
        jFTtelefone.setText(null);
        jTFendereco.setText(null);
        jTFnumero.setText(null);
        jTFbairro.setText(null);
        jTFcidade.setText(null);
        jTFestado.setText(null);
        jFTcep.setText(null);

    }
}
