/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.DAOativos;
import DAO.DAOlocacaoAtivos;
import DAO.DAOusuarios;
import Model.Ativos;
import Model.LocacaoAtivos;
import Model.Usuarios;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Familia
 */
public class cadLocacaoAtivos extends javax.swing.JFrame {

    /**
     * Creates new form LocacaoAtivos
     */
    DAOlocacaoAtivos daolocatv = new DAOlocacaoAtivos();
    LocacaoAtivos locatv;
    SimpleDateFormat df;
    
    public cadLocacaoAtivos() {
        initComponents();
        
        /** habilita barra de rolagem quando necessário */
        jTableEquip.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        
        /** habilita a ordenação por colunas */
        jTableEquip.setRowSorter(new TableRowSorter());
        jTableEquip.setAutoCreateRowSorter(true);
        jFTdatadev.setVisible(false);
        jLdatadev.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTFdescricao = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTFmodelo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTFfabricante = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTFnumserie = new javax.swing.JTextField();
        jTFidequip = new javax.swing.JTextField();
        jLid = new javax.swing.JLabel();
        jBidequip = new javax.swing.JButton();
        jTFtipo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jTFiduser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTFnome = new javax.swing.JTextField();
        jLnome = new javax.swing.JLabel();
        jTFsobrenome = new javax.swing.JTextField();
        jLnome1 = new javax.swing.JLabel();
        jLnome7 = new javax.swing.JLabel();
        jTFdepartamento = new javax.swing.JTextField();
        jTFemail = new javax.swing.JTextField();
        jLnome4 = new javax.swing.JLabel();
        jTFtelefone = new javax.swing.JTextField();
        jLnome2 = new javax.swing.JLabel();
        jLnome3 = new javax.swing.JLabel();
        jTFramal = new javax.swing.JTextField();
        jBiduser = new javax.swing.JButton();
        jBTlocacao = new javax.swing.JButton();
        jBTcancelar = new javax.swing.JButton();
        jBTdevolucao = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLidloc = new javax.swing.JLabel();
        jLdatadev = new javax.swing.JLabel();
        jFTdataloc = new javax.swing.JFormattedTextField();
        jFTdatadev = new javax.swing.JFormattedTextField();
        jLdataloc1 = new javax.swing.JLabel();
        jTFidelocacao = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEquip = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jRBtodos = new javax.swing.JRadioButton();
        jRBlocados = new javax.swing.JRadioButton();
        jRBnlocados = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Informações do Ativo"));
        jPanel3.setPreferredSize(new java.awt.Dimension(300, 177));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTFdescricao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTFdescricao.setEnabled(false);
        jTFdescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFdescricaoActionPerformed(evt);
            }
        });
        jPanel3.add(jTFdescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 56, 253, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Descrição:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 34, 193, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Modelo:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 88, -1, -1));

        jTFmodelo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTFmodelo.setEnabled(false);
        jTFmodelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFmodeloActionPerformed(evt);
            }
        });
        jPanel3.add(jTFmodelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 109, 146, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Fabricante:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 88, -1, -1));

        jTFfabricante.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTFfabricante.setEnabled(false);
        jTFfabricante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFfabricanteActionPerformed(evt);
            }
        });
        jPanel3.add(jTFfabricante, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 109, 115, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Número de Série:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 88, -1, -1));

        jTFnumserie.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTFnumserie.setEnabled(false);
        jTFnumserie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFnumserieActionPerformed(evt);
            }
        });
        jPanel3.add(jTFnumserie, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 109, 310, -1));

        jTFidequip.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTFidequip.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFidequipFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFidequipFocusLost(evt);
            }
        });
        jTFidequip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFidequipActionPerformed(evt);
            }
        });
        jTFidequip.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTFidequipPropertyChange(evt);
            }
        });
        jPanel3.add(jTFidequip, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 56, 100, -1));

        jLid.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLid.setText("ID do Equip.:");
        jPanel3.add(jLid, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 30, -1, -1));

        jBidequip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Search.png"))); // NOI18N
        jBidequip.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jPanel3.add(jBidequip, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 56, -1, 21));

        jTFtipo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTFtipo.setEnabled(false);
        jTFtipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFtipoActionPerformed(evt);
            }
        });
        jPanel3.add(jTFtipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 56, 190, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Tipo:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 34, 69, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Informações do Usuário"));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTFiduser.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTFiduser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFiduserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFiduserFocusLost(evt);
            }
        });
        jTFiduser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFiduserActionPerformed(evt);
            }
        });
        jPanel4.add(jTFiduser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 70, -1));

        jLabel2.setText("ID:");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jTFnome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTFnome.setEnabled(false);
        jTFnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFnomeActionPerformed(evt);
            }
        });
        jPanel4.add(jTFnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 470, -1));

        jLnome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLnome.setText("Nome:");
        jPanel4.add(jLnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));

        jTFsobrenome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTFsobrenome.setEnabled(false);
        jPanel4.add(jTFsobrenome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 350, -1));

        jLnome1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLnome1.setText("Sobrenome:");
        jPanel4.add(jLnome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLnome7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLnome7.setText("Departamento:");
        jPanel4.add(jLnome7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, -1, -1));

        jTFdepartamento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTFdepartamento.setEnabled(false);
        jTFdepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFdepartamentoActionPerformed(evt);
            }
        });
        jPanel4.add(jTFdepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 180, -1));

        jTFemail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTFemail.setEnabled(false);
        jPanel4.add(jTFemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 330, -1));

        jLnome4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLnome4.setText("E-mail:");
        jPanel4.add(jLnome4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jTFtelefone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTFtelefone.setEnabled(false);
        jPanel4.add(jTFtelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 150, -1));

        jLnome2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLnome2.setText("Telefone:");
        jPanel4.add(jLnome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, -1, -1));

        jLnome3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLnome3.setText("Ramal:");
        jPanel4.add(jLnome3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, -1, -1));

        jTFramal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTFramal.setEnabled(false);
        jPanel4.add(jTFramal, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, 80, -1));

        jBiduser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Search.png"))); // NOI18N
        jBiduser.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jPanel4.add(jBiduser, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, 21));

        jBTlocacao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jBTlocacao.setText("Confirmar Locação");
        jBTlocacao.setEnabled(false);
        jBTlocacao.setPreferredSize(new java.awt.Dimension(120, 30));
        jBTlocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTlocacaoActionPerformed(evt);
            }
        });
        jPanel4.add(jBTlocacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 145, -1));

        jBTcancelar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jBTcancelar.setText("Cancelar");
        jBTcancelar.setEnabled(false);
        jBTcancelar.setPreferredSize(new java.awt.Dimension(120, 30));
        jBTcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTcancelarActionPerformed(evt);
            }
        });
        jPanel4.add(jBTcancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 145, -1));

        jBTdevolucao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jBTdevolucao.setText("Devolução");
        jBTdevolucao.setEnabled(false);
        jBTdevolucao.setPreferredSize(new java.awt.Dimension(120, 30));
        jBTdevolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTdevolucaoActionPerformed(evt);
            }
        });
        jPanel4.add(jBTdevolucao, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, 145, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Locação"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLidloc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLidloc.setText("ID da Locação:");
        jPanel2.add(jLidloc, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLdatadev.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLdatadev.setText("Data de devolução:");
        jPanel2.add(jLdatadev, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, -1, -1));

        try {
            jFTdataloc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTdataloc.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jFTdataloc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(jFTdataloc, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 100, -1));

        try {
            jFTdatadev.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTdatadev.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jFTdatadev.setEnabled(false);
        jFTdatadev.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(jFTdatadev, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, 106, -1));

        jLdataloc1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLdataloc1.setText("Data de locação:");
        jPanel2.add(jLdataloc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        jTFidelocacao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTFidelocacao.setEnabled(false);
        jTFidelocacao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFidelocacaoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFidelocacaoFocusLost(evt);
            }
        });
        jTFidelocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFidelocacaoActionPerformed(evt);
            }
        });
        jTFidelocacao.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTFidelocacaoPropertyChange(evt);
            }
        });
        jPanel2.add(jTFidelocacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 100, -1));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Locação / Devolução", jPanel5);

        jPanel7.setFocusTraversalPolicyProvider(true);

        jTableEquip.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "DESCRIÇÃO", "TIPO", "MODELO", "FABRICANTE", "Nº DE SÉRIE", "LOCADO", "ID DE LOCAÇÃO", "DATA LOCAÇÃO", "DEVOLUÇÃO", "ID USER", "USUÁRIO", "SOBRENOME", "DEPARTAMENTO", "E-MAIL", "TELEFONE", "RAMAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableEquip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableEquipMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableEquip);
        if (jTableEquip.getColumnModel().getColumnCount() > 0) {
            jTableEquip.getColumnModel().getColumn(0).setMinWidth(50);
            jTableEquip.getColumnModel().getColumn(1).setMinWidth(100);
            jTableEquip.getColumnModel().getColumn(2).setMinWidth(80);
            jTableEquip.getColumnModel().getColumn(3).setMinWidth(100);
            jTableEquip.getColumnModel().getColumn(4).setMinWidth(100);
            jTableEquip.getColumnModel().getColumn(5).setMinWidth(100);
            jTableEquip.getColumnModel().getColumn(6).setMinWidth(60);
            jTableEquip.getColumnModel().getColumn(7).setMinWidth(100);
            jTableEquip.getColumnModel().getColumn(8).setMinWidth(100);
            jTableEquip.getColumnModel().getColumn(9).setMinWidth(150);
            jTableEquip.getColumnModel().getColumn(10).setMinWidth(100);
            jTableEquip.getColumnModel().getColumn(11).setMinWidth(50);
        }

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Filtros"));
        jPanel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel6.setPreferredSize(new java.awt.Dimension(1015, 50));

        buttonGroup1.add(jRBtodos);
        jRBtodos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRBtodos.setSelected(true);
        jRBtodos.setText("Todos equipamentos");
        jRBtodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBtodosActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRBlocados);
        jRBlocados.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRBlocados.setText("Equipamentos Locados");
        jRBlocados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBlocadosActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRBnlocados);
        jRBnlocados.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRBnlocados.setText("Equipamentos não Locados");
        jRBnlocados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBnlocadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jRBtodos)
                .addGap(32, 32, 32)
                .addComponent(jRBlocados)
                .addGap(28, 28, 28)
                .addComponent(jRBnlocados)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBtodos)
                    .addComponent(jRBlocados)
                    .addComponent(jRBnlocados))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Lista de Equipamentos", jPanel7);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(813, 636));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTFidequipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFidequipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFidequipActionPerformed

    private void jTFidequipPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTFidequipPropertyChange
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFidequipPropertyChange

    private void jTFidequipFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFidequipFocusLost
        
        try {
            
            if(! jTFidequip.getText().isEmpty()){           
                DAOlocacaoAtivos daoloc = new DAOlocacaoAtivos();
                LocacaoAtivos locacao;
                locacao = daoloc.consultarLocacaoEquip(Integer.parseInt(jTFidequip.getText()));
                System.out.println("ID do Equipamento: "+locacao.getIdequipe());
            if ((locacao.getIdequipe() != 0 )){
                System.out.println("ID do Equipamento é diferente de 0 ");
                df = new SimpleDateFormat("dd/MM/yyyy");
                if(locacao.isLocado() && jTFiduser.getText().isEmpty()){
                    System.out.println("Ativo locado: "+ locacao.isLocado()+jTFiduser.getText().isEmpty());
                    jTFdescricao.setText(locacao.getDescricao());
                    jTFtipo.setText(locacao.getTipo());
                    jTFmodelo.setText(locacao.getModelo());
                    jTFfabricante.setText(locacao.getFabricante());
                    jTFnumserie.setText(locacao.getNumserie());
                    Date Hoje = new Date();    
                    String hoje = df.format(Hoje);
                    jFTdataloc.setText(hoje);
                    
                    if(locacao.isLocado()){     
                        /*
                        Date Date = locacao.getDatalocacao();*/
                        String date = df.format(locacao.getDatalocacao());

                        jFTdataloc.setText(date);
                        jTFiduser.setText(String.valueOf(locacao.getUsuarios_usu_id()));
                        jTFnome.setText(locacao.getNome());
                        jTFsobrenome.setText(locacao.getSobrenome());
                        jTFtelefone.setText(locacao.getTelefone());
                        jTFramal.setText(locacao.getRamal());
                        jTFemail.setText(locacao.getEmail());
                        jTFdepartamento.setText(locacao.getDepartamento());
                        devolver();
                    }else{
                        
                        jTFiduser.setEnabled(true);
                        jFTdataloc.setEnabled(true);
                        jTFidequip.setEnabled(true);
                        jBTdevolucao.setEnabled(false);
                        jBTcancelar.setEnabled(true);
                        
                    }
                }else if(!locacao.isLocado()){
                    System.out.println("Ativo locado: "+ locacao.isLocado()+jTFiduser.getText().isEmpty());
                    jTFdescricao.setText(locacao.getDescricao());
                    jTFtipo.setText(locacao.getTipo());
                    jTFmodelo.setText(locacao.getModelo());
                    jTFfabricante.setText(locacao.getFabricante());
                    jTFnumserie.setText(locacao.getNumserie());
                    Date Hoje = new Date();    
                    String hoje = df.format(Hoje);
                    jFTdataloc.setText(hoje);
                    locar();
                }
                else{
                    JOptionPane.showMessageDialog(this, "Este ativo já está locado para o usuário:"
                            + locacao.getNome()+" "+locacao.getSobrenome()+" do Depto. "+locacao.getDepartamento());
                    clearequip();
                    clearuser();
                    cancelar();
                }
                
            }else{
                //System.out.println("Ativo invalido: "+ atv.getDescricao());
                clearequip();
                JOptionPane.showMessageDialog(this, "Ativo não encontrado!", "Informação!", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        } catch (Exception e) {
            clearequip();
            JOptionPane.showMessageDialog(this, "Valor inválido! Só é permitido números inteiros", "Erro!", JOptionPane.WARNING_MESSAGE);
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFidequipFocusLost

    private void jTFdescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFdescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFdescricaoActionPerformed

    private void jTFmodeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFmodeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFmodeloActionPerformed

    private void jTFfabricanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFfabricanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFfabricanteActionPerformed

    private void jTFnumserieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFnumserieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFnumserieActionPerformed

    private void jTFiduserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFiduserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFiduserActionPerformed

    private void jTFdepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFdepartamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFdepartamentoActionPerformed

    private void jTFidequipFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFidequipFocusGained
        //clearequip();
        //clearuser();
        //jTFiduser.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFidequipFocusGained

    private void jTFiduserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFiduserFocusLost
        
        try {
            if(! jTFiduser.getText().isEmpty()){
                DAOusuarios daouser = new DAOusuarios();
                Usuarios user = new Usuarios(); 
                user = daouser.consultaUsuario(Integer.parseInt(jTFiduser.getText()));
                
                if(!(user.getNome() == null)){
                    jTFnome.setText(user.getNome());
                    jTFsobrenome.setText(user.getSobreNome());
                    jTFtelefone.setText(user.getTelefone());
                    jTFramal.setText(user.getRamal());
                    jTFemail.setText(user.getEmail());
                    jTFdepartamento.setText(user.getDepartamento());
                    //jTFiduser.setEnabled(false);
                    if(!(jTFidequip.getText().isEmpty())){
                        jBTlocacao.setEnabled(true);
                        jBTdevolucao.setEnabled(false);
                    }
                    /*
                    DAOlocacaoAtivos daoloc = new DAOlocacaoAtivos();
                    LocacaoAtivos locacao;
                    locacao = daoloc.consultarLocacaoUser(user.getId());
                    try {
                        if(locacao.getId() != 0){
                            Date Datedb = locacao.getDatalocacao();
                            SimpleDateFormat df;
                            df = new SimpleDateFormat("dd/MM/yyyy");
                            String date = df.format(Datedb);
                            jFTdataloc.setText(date);
                            jTFidequip.setText(String.valueOf(locacao.getIdequipe()));
                            jTFdescricao.setText(locacao.getDescricao());
                            jTFtipo.setText(locacao.getTipo());
                            jTFmodelo.setText(locacao.getModelo());
                            jTFfabricante.setText(locacao.getFabricante());
                            jTFnumserie.setText(locacao.getNumserie());
                            jTFidequip.setEnabled(false);
                            jTFiduser.setEnabled(false);
                        }else{
                            jTFidequip.setEnabled(true);
                        }
                    } catch (Exception e){
                        //clearequip();
                    } 
                    */
                }else{
                            jTFiduser.setEnabled(false);
                    clearuser();
                    JOptionPane.showMessageDialog(this, "Usuário não encontrado!", "Informação!", JOptionPane.INFORMATION_MESSAGE);
                }
                
            }
        } catch (Exception e) {
            clearuser();
            JOptionPane.showMessageDialog(this, "Valor inválido! Só é permitido números inteiros", "Erro!", JOptionPane.WARNING_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFiduserFocusLost

    private void jTFiduserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFiduserFocusGained
        //clearuser();
        //clearequip();
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFiduserFocusGained

    private void jBTlocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTlocacaoActionPerformed
        int ret;
        ret = JOptionPane.showConfirmDialog(rootPane, "Confirma a Devolução do Equipamento: ", "Confirmação", JOptionPane.YES_NO_OPTION);
        if(ret == JOptionPane.YES_OPTION){
            
            DAOlocacaoAtivos daoloc = new DAOlocacaoAtivos();
            LocacaoAtivos locatv = new LocacaoAtivos();
            //converte Data java para formato Data SQL
            java.util.Date dt = new java.util.Date();
            java.sql.Date date = new java.sql.Date(dt.getTime());
            //System.out.println(" Data convertida "+date);
            try {
                locatv.setDatalocacao(date);
                locatv.setUsuarios_usu_id(Integer.parseInt(jTFiduser.getText()));
                locatv.setIdequipe(Integer.parseInt(jTFidequip.getText()));

                daoloc.adicionarLocacaoAtivos(locatv);
                cancelar();
                JOptionPane.showMessageDialog(rootPane, "Ativo locado com sucesso!");
                
            } catch (Exception e) {
                System.out.println("Erro ao gravar locação: "+e);
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "Ação Cancelada!");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jBTlocacaoActionPerformed

    private void jTFtipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFtipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFtipoActionPerformed

    private void jBTcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTcancelarActionPerformed
        clearuser();
        clearequip();
        //jBTlocacao.setEnabled(false);
        cancelar();
        // TODO add your handling code here:
    }//GEN-LAST:event_jBTcancelarActionPerformed

    private void jTFnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFnomeActionPerformed

    private void jRBtodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBtodosActionPerformed
        carregaEquipto();
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBtodosActionPerformed

    private void jRBlocadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBlocadosActionPerformed
        carregaLocados();
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBlocadosActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        //verifica se o focu da aba mudou
        if (jTabbedPane1.getSelectedIndex() == 1){
            if(jRBtodos.isSelected()){
                carregaEquipto();
            }else if(jRBlocados.isSelected()){
                carregaLocados();
            }else{
                carregaNaoLocados();
            }
            
        }
        System.out.println("Mudou "+jTabbedPane1.getSelectedIndex());
            // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void jRBnlocadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBnlocadosActionPerformed
        carregaNaoLocados();
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBnlocadosActionPerformed

    private void jTableEquipMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEquipMouseClicked
        
        jTabbedPane1.setSelectedIndex(0);
        cancelar();
        clearuser();
        jTFidequip.setText(String.valueOf(jTableEquip.getModel().getValueAt(jTableEquip.getSelectedRow(), 0)));
        jTFdescricao.setText(String.valueOf(jTableEquip.getModel().getValueAt(jTableEquip.getSelectedRow(), 1)));
        jTFtipo.setText(String.valueOf(jTableEquip.getModel().getValueAt(jTableEquip.getSelectedRow(), 2)));
        jTFmodelo.setText(String.valueOf(jTableEquip.getModel().getValueAt(jTableEquip.getSelectedRow(), 3)));
        jTFfabricante.setText(String.valueOf(jTableEquip.getModel().getValueAt(jTableEquip.getSelectedRow(), 4)));
        jTFnumserie.setText(String.valueOf(jTableEquip.getModel().getValueAt(jTableEquip.getSelectedRow(), 5)));
        
        if(! jRBnlocados.isSelected()){
            if(jTableEquip.getModel().getValueAt(jTableEquip.getSelectedRow(), 6).equals("SIM")){

                jTFidelocacao.setText(String.valueOf(jTableEquip.getModel().getValueAt(jTableEquip.getSelectedRow(), 7)));
                df = new SimpleDateFormat("dd/MM/yyyy");
                Date Date = (Date) jTableEquip.getModel().getValueAt(jTableEquip.getSelectedRow(), 8);
                String date = df.format(Date);
                jFTdataloc.setText(date);
                jFTdatadev.setText(String.valueOf(jTableEquip.getModel().getValueAt(jTableEquip.getSelectedRow(), 9)));
                jTFiduser.setText(String.valueOf(jTableEquip.getModel().getValueAt(jTableEquip.getSelectedRow(), 10)));
                jTFnome.setText(String.valueOf(jTableEquip.getModel().getValueAt(jTableEquip.getSelectedRow(), 11)));
                jTFsobrenome.setText(String.valueOf(jTableEquip.getModel().getValueAt(jTableEquip.getSelectedRow(), 12)));
                jTFdepartamento.setText(String.valueOf(jTableEquip.getModel().getValueAt(jTableEquip.getSelectedRow(), 13)));
                jTFemail.setText(String.valueOf(jTableEquip.getModel().getValueAt(jTableEquip.getSelectedRow(), 14)));
                jTFtelefone.setText(String.valueOf(jTableEquip.getModel().getValueAt(jTableEquip.getSelectedRow(), 15)));
                jTFramal.setText(String.valueOf(jTableEquip.getModel().getValueAt(jTableEquip.getSelectedRow(), 16)));


                devolver();
            }else{
                Date Hoje = new Date();
                df = new SimpleDateFormat("dd/MM/yyyy");
                String hoje = df.format(Hoje);
                jFTdataloc.setText(hoje);

                locar();
            }
        }else{
            
            Date Hoje = new Date();
            df = new SimpleDateFormat("dd/MM/yyyy");
            String hoje = df.format(Hoje);
            jFTdataloc.setText(hoje);

            locar();
        }
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableEquipMouseClicked

    private void jBTdevolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTdevolucaoActionPerformed
        
        //locatv = daolocatv.consultarLocacaoEquip(Integer.parseInt(jTFidequip.getText()));
        //System.out.println("ID de locação é: "+locatv.getId());
        int ret;
        ret = JOptionPane.showConfirmDialog(rootPane, "Confirma a Devolução do Equipamento: ", "Confirmação", JOptionPane.YES_NO_OPTION);
        if(ret == JOptionPane.YES_OPTION){
            //java.util.Date dt = new java.util.Date();
            //java.sql.Date date = new java.sql.Date(dt.getTime());
            java.util.Date dt = new java.util.Date();
            Timestamp date = new java.sql.Timestamp(dt.getTime());
            daolocatv.devolverEquip(Integer.parseInt(jTFidequip.getText()), date, Integer.parseInt(jTFidelocacao.getText()));
            JOptionPane.showMessageDialog(rootPane, "Equipamento devolvido.");
            cancelar();
            clearequip();
            clearuser();
        }else{
            JOptionPane.showMessageDialog(rootPane, "Ação Cancelada!");
        }
                        
        // TODO add your handling code here:
    }//GEN-LAST:event_jBTdevolucaoActionPerformed

    private void jTFidelocacaoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFidelocacaoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFidelocacaoFocusGained

    private void jTFidelocacaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFidelocacaoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFidelocacaoFocusLost

    private void jTFidelocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFidelocacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFidelocacaoActionPerformed

    private void jTFidelocacaoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTFidelocacaoPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFidelocacaoPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadLocacaoAtivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadLocacaoAtivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadLocacaoAtivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadLocacaoAtivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadLocacaoAtivos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBTcancelar;
    private javax.swing.JButton jBTdevolucao;
    private javax.swing.JButton jBTlocacao;
    private javax.swing.JButton jBidequip;
    private javax.swing.JButton jBiduser;
    private javax.swing.JFormattedTextField jFTdatadev;
    private javax.swing.JFormattedTextField jFTdataloc;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLdatadev;
    private javax.swing.JLabel jLdataloc1;
    private javax.swing.JLabel jLid;
    private javax.swing.JLabel jLidloc;
    private javax.swing.JLabel jLnome;
    private javax.swing.JLabel jLnome1;
    private javax.swing.JLabel jLnome2;
    private javax.swing.JLabel jLnome3;
    private javax.swing.JLabel jLnome4;
    private javax.swing.JLabel jLnome7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRBlocados;
    private javax.swing.JRadioButton jRBnlocados;
    private javax.swing.JRadioButton jRBtodos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFdepartamento;
    private javax.swing.JTextField jTFdescricao;
    private javax.swing.JTextField jTFemail;
    private javax.swing.JTextField jTFfabricante;
    private javax.swing.JTextField jTFidelocacao;
    private javax.swing.JTextField jTFidequip;
    private javax.swing.JTextField jTFiduser;
    private javax.swing.JTextField jTFmodelo;
    private javax.swing.JTextField jTFnome;
    private javax.swing.JTextField jTFnumserie;
    private javax.swing.JTextField jTFramal;
    private javax.swing.JTextField jTFsobrenome;
    private javax.swing.JTextField jTFtelefone;
    private javax.swing.JTextField jTFtipo;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableEquip;
    // End of variables declaration//GEN-END:variables

    public void clearequip(){
        jTFidequip.setText(null);
        jTFtipo.setText(null);
        jTFdescricao.setText(null);
        jTFmodelo.setText(null);
        jTFfabricante.setText(null);
        jTFnumserie.setText(null);
        jTFidequip.setEnabled(true);
        jFTdataloc.setEnabled(true);
        jFTdataloc.setText(null);
        jTFidelocacao.setText(null);
    }

    public void cancelar(){
        jBTlocacao.setEnabled(false);
        jBTcancelar.setEnabled(false);
        jBidequip.setEnabled(true);
        jBiduser.setEnabled(true);
        jBTdevolucao.setEnabled(false);
    }
    
    public void locar(){
        jBTlocacao.setEnabled(true);
        jBTcancelar.setEnabled(true);
        jBidequip.setEnabled(false);
        jBiduser.setEnabled(true);
    }
    
    public void devolver(){
        jBTlocacao.setEnabled(false);
        jBTcancelar.setEnabled(true);
        jBidequip.setEnabled(false);
        jTFidequip.setEnabled(false);
        jTFiduser.setEnabled(false);
        jFTdataloc.setEnabled(false);
        jBiduser.setEnabled(false);
        jBTdevolucao.setEnabled(true);
        
    }
    
    public void clearuser(){
        jTFiduser.setText(null);
        jTFnome.setText(null);
        jTFsobrenome.setText(null);
        jTFtelefone.setText(null);
        jTFramal.setText(null);
        jTFemail.setText(null);
        jTFdepartamento.setText(null);
        jTFiduser.setEnabled(true);
        jFTdataloc.setEnabled(true);
        jFTdataloc.setText(null);
    }


    public void carregaEquipto(){
        
        List<LocacaoAtivos> listlocacao = new ArrayList();
        if(jRBtodos.isSelected()){
            listlocacao = daolocatv.listaEquip();
        }else if(jRBlocados.isSelected()){
            listlocacao = daolocatv.listaEquip();
        }
        DefaultTableModel model = (DefaultTableModel) jTableEquip.getModel();
        model.setNumRows(0);
        
        for (int i=0; i < listlocacao.size(); i++){
         locatv = listlocacao.get(i);
         String locado = null;
            if(locatv.isLocado()){
                locado = "SIM";
            }else{
                locado = "NÃO";
            }
         model.addRow(new Object[]{locatv.getIdequipe(), locatv.getDescricao(), locatv.getTipo(), 
             locatv.getModelo(), locatv.getFabricante(), locatv.getNumserie(), locado, locatv.getId(), locatv.getDatalocacao(), locatv.getDatadevolucao(),
             locatv.getUsuarios_usu_id(), locatv.getNome(), locatv.getSobrenome(), locatv.getDepartamento(), locatv.getEmail(), locatv.getTelefone(), locatv.getRamal()});
                 
        }
    }


    public void carregaLocados(){
        
        List<LocacaoAtivos> listlocacao = new ArrayList();
        if(jRBtodos.isSelected()){
            listlocacao = daolocatv.listaEquip();
        }else if(jRBlocados.isSelected()){
            listlocacao = daolocatv.listaEquipLocados();
        }
        DefaultTableModel model = (DefaultTableModel) jTableEquip.getModel();
        model.setNumRows(0);
        
        for (int i=0; i < listlocacao.size(); i++){
         locatv = listlocacao.get(i);
         String locado = null;
            if(locatv.getNome() != null){
                locado = "SIM";
            }else{
                locado = "NÃO";
            }
         model.addRow(new Object[]{locatv.getIdequipe(), locatv.getDescricao(), locatv.getTipo(), 
             locatv.getModelo(), locatv.getFabricante(), locatv.getNumserie(), locado, locatv.getId(), locatv.getDatalocacao(), locatv.getDatadevolucao(),
             locatv.getUsuarios_usu_id(), locatv.getNome(), locatv.getSobrenome(), locatv.getDepartamento(), locatv.getEmail(), locatv.getTelefone(), locatv.getRamal()});
                 
        }
    }

    public void carregaNaoLocados(){
        /*
        List<LocacaoAtivos> listlocacao = new ArrayList();
        listlocacao = daolocatv.listaEquipNaoLocados();
        */
        List<Ativos> listaatv = new ArrayList();
        DAOativos daoatv = new DAOativos();
        Ativos atv;
        listaatv = daoatv.listaAtivosLocado();
        
        DefaultTableModel model = (DefaultTableModel) jTableEquip.getModel();
        model.setNumRows(0);       
        
        System.out.println("Locado é igual : ");
        for (int i=0; i < listaatv.size(); i++){
         atv = listaatv.get(i);
         System.out.println("Locado é igual : "+atv.getLocado());
         String locado = null;          
            
         model.addRow(new Object[]{atv.getId(), atv.getDescricao(), atv.getTipo(), 
             atv.getModelo(), atv.getFabricante(), atv.getNum_serie(), atv.getLocado() });
         
        //esconder coluna
        //jTableEquip.getColumnModel().getColumn(0).setMinWidth(0);
        //jTableEquip.getColumnModel().getColumn(0).setMaxWidth(0);
      
        }
        
    }
}
