/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.DAOusuarios;
import DAO.DAOperfil;
import DAO.DAOdepartamento;
import Model.Departamento;
import Model.Perfil;
import Model.Usuarios;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Colin
 */


public class CadUsuario extends javax.swing.JFrame {

    DAOusuarios daousu = new DAOusuarios();
    Usuarios usu = new Usuarios();
    Usuarios usulist;
    
        
    /**
     * Creates new form CadUsuarios
     */
    public CadUsuario() {
        initComponents();
        
        jTableusuarios.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        //jTableusuarios.setAutoscrolls(true);
        
        /** habilita a ordenação por colunas */
        jTableusuarios.setRowSorter(new TableRowSorter());
        jTableusuarios.setAutoCreateRowSorter(true);

        carregaUsuarios(); carregaPerfil(); 
        carregaDepartamento();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLnome = new javax.swing.JLabel();
        jTFnome = new javax.swing.JTextField();
        jLnome1 = new javax.swing.JLabel();
        jTFsobrenome = new javax.swing.JTextField();
        jTFtelefone = new javax.swing.JTextField();
        jLnome2 = new javax.swing.JLabel();
        jLnome3 = new javax.swing.JLabel();
        jTFramal = new javax.swing.JTextField();
        jLnome4 = new javax.swing.JLabel();
        jTFemail = new javax.swing.JTextField();
        jCBperfil = new javax.swing.JComboBox<>();
        jCBdepartamento = new javax.swing.JComboBox<>();
        jLnome6 = new javax.swing.JLabel();
        jLnome7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTFid = new javax.swing.JTextField();
        jBTpesquisar_id = new javax.swing.JButton();
        jBTpesquisar_email = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jCBstatus = new javax.swing.JComboBox<>();
        jBTsenha = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jBTnovo = new javax.swing.JButton();
        jBTeditar = new javax.swing.JButton();
        jBTsalvar = new javax.swing.JButton();
        jBTexcluir = new javax.swing.JButton();
        jBTcancelar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableusuarios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Usuários");
        setResizable(false);

        jPanel1.setForeground(new java.awt.Color(255, 204, 102));
        jPanel1.setToolTipText("");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder()));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLnome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLnome.setText("Nome:");
        jPanel2.add(jLnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        jTFnome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTFnome.setEnabled(false);
        jPanel2.add(jTFnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 250, -1));

        jLnome1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLnome1.setText("Sobrenome:");
        jPanel2.add(jLnome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jTFsobrenome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTFsobrenome.setEnabled(false);
        jPanel2.add(jTFsobrenome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 350, -1));

        jTFtelefone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTFtelefone.setEnabled(false);
        jPanel2.add(jTFtelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 150, -1));

        jLnome2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLnome2.setText("Telefone:");
        jPanel2.add(jLnome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLnome3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLnome3.setText("Ramal:");
        jPanel2.add(jLnome3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, -1));

        jTFramal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTFramal.setEnabled(false);
        jPanel2.add(jTFramal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 80, -1));

        jLnome4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLnome4.setText("E-mail:");
        jPanel2.add(jLnome4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jTFemail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTFemail.setEnabled(false);
        jPanel2.add(jTFemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 300, -1));

        jCBperfil.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCBperfil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o Perfil" }));
        jCBperfil.setEnabled(false);
        jPanel2.add(jCBperfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 180, -1));

        jCBdepartamento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCBdepartamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o Departamento" }));
        jCBdepartamento.setEnabled(false);
        jPanel2.add(jCBdepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 180, -1));

        jLnome6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLnome6.setText("Perfil:");
        jPanel2.add(jLnome6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, -1, -1));

        jLnome7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLnome7.setText("Departamento:");
        jPanel2.add(jLnome7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro de Usuários");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 11, 590, 30));

        jLabel2.setText("ID:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jTFid.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTFid.setEnabled(false);
        jTFid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFidActionPerformed(evt);
            }
        });
        jPanel2.add(jTFid, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 50, -1));

        jBTpesquisar_id.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Search.png"))); // NOI18N
        jBTpesquisar_id.setToolTipText("Pesquisar ID");
        jBTpesquisar_id.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jBTpesquisar_id.setPreferredSize(new java.awt.Dimension(24, 24));
        jBTpesquisar_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTpesquisar_idActionPerformed(evt);
            }
        });
        jPanel2.add(jBTpesquisar_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        jBTpesquisar_email.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Search.png"))); // NOI18N
        jBTpesquisar_email.setToolTipText("Pesquisar E-mail");
        jBTpesquisar_email.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jBTpesquisar_email.setPreferredSize(new java.awt.Dimension(24, 24));
        jPanel2.add(jBTpesquisar_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, -1, -1));

        jLabel3.setText("Status:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, -1, -1));

        jCBstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o Status", "Ativo", "Inativo" }));
        jCBstatus.setEnabled(false);
        jPanel2.add(jCBstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 180, -1));

        jBTsenha.setText("Resetar Senha");
        jBTsenha.setEnabled(false);
        jBTsenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTsenhaActionPerformed(evt);
            }
        });
        jPanel2.add(jBTsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, -1, 30));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setPreferredSize(new java.awt.Dimension(610, 56));

        jBTnovo.setText("Novo");
        jBTnovo.setMargin(new java.awt.Insets(2, 5, 2, 5));
        jBTnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTnovoActionPerformed(evt);
            }
        });

        jBTeditar.setText("Editar");
        jBTeditar.setEnabled(false);
        jBTeditar.setMargin(new java.awt.Insets(2, 5, 2, 5));
        jBTeditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTeditarActionPerformed(evt);
            }
        });

        jBTsalvar.setText("Salvar");
        jBTsalvar.setEnabled(false);
        jBTsalvar.setMargin(new java.awt.Insets(2, 5, 2, 5));
        jBTsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTsalvarActionPerformed(evt);
            }
        });

        jBTexcluir.setText("Excluir");
        jBTexcluir.setEnabled(false);
        jBTexcluir.setMargin(new java.awt.Insets(2, 5, 2, 5));
        jBTexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTexcluirActionPerformed(evt);
            }
        });

        jBTcancelar.setText("Cancelar");
        jBTcancelar.setEnabled(false);
        jBTcancelar.setMargin(new java.awt.Insets(2, 5, 2, 5));
        jBTcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTcancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jBTnovo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBTeditar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jBTsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBTexcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jBTcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBTeditar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBTexcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBTsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBTcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBTnovo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jScrollPane1.setBorder(null);
        jScrollPane1.setForeground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(200, 419));

        jTableusuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Sobre Nome", "Telefone", "Ramal", "E-mail", "Status", "Perfil", "Departamento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableusuarios.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jTableusuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableusuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableusuarios);
        if (jTableusuarios.getColumnModel().getColumnCount() > 0) {
            jTableusuarios.getColumnModel().getColumn(0).setMinWidth(30);
            jTableusuarios.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTableusuarios.getColumnModel().getColumn(0).setMaxWidth(100);
            jTableusuarios.getColumnModel().getColumn(0).setHeaderValue("ID");
            jTableusuarios.getColumnModel().getColumn(1).setMinWidth(60);
            jTableusuarios.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTableusuarios.getColumnModel().getColumn(1).setHeaderValue("Nome");
            jTableusuarios.getColumnModel().getColumn(2).setMinWidth(150);
            jTableusuarios.getColumnModel().getColumn(2).setHeaderValue("Sobre Nome");
            jTableusuarios.getColumnModel().getColumn(3).setMinWidth(100);
            jTableusuarios.getColumnModel().getColumn(3).setHeaderValue("Telefone");
            jTableusuarios.getColumnModel().getColumn(4).setMinWidth(40);
            jTableusuarios.getColumnModel().getColumn(4).setPreferredWidth(50);
            jTableusuarios.getColumnModel().getColumn(4).setMaxWidth(80);
            jTableusuarios.getColumnModel().getColumn(4).setHeaderValue("Ramal");
            jTableusuarios.getColumnModel().getColumn(5).setMinWidth(150);
            jTableusuarios.getColumnModel().getColumn(5).setPreferredWidth(150);
            jTableusuarios.getColumnModel().getColumn(5).setMaxWidth(200);
            jTableusuarios.getColumnModel().getColumn(5).setHeaderValue("E-mail");
            jTableusuarios.getColumnModel().getColumn(6).setMinWidth(30);
            jTableusuarios.getColumnModel().getColumn(6).setPreferredWidth(50);
            jTableusuarios.getColumnModel().getColumn(6).setMaxWidth(100);
            jTableusuarios.getColumnModel().getColumn(6).setHeaderValue("Status");
            jTableusuarios.getColumnModel().getColumn(7).setMinWidth(50);
            jTableusuarios.getColumnModel().getColumn(7).setPreferredWidth(50);
            jTableusuarios.getColumnModel().getColumn(7).setMaxWidth(80);
            jTableusuarios.getColumnModel().getColumn(7).setHeaderValue("Perfil");
            jTableusuarios.getColumnModel().getColumn(8).setMinWidth(150);
            jTableusuarios.getColumnModel().getColumn(8).setPreferredWidth(150);
            jTableusuarios.getColumnModel().getColumn(8).setHeaderValue("Departamento");
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(626, 573));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTFidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFidActionPerformed

    private void jBTcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTcancelarActionPerformed
        cancelar(); clear();
        // TODO add your handling code here:
    }//GEN-LAST:event_jBTcancelarActionPerformed

    private void jBTeditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTeditarActionPerformed
        editar();
        // TODO add your handling code here:
    }//GEN-LAST:event_jBTeditarActionPerformed

    private void jBTnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTnovoActionPerformed
        clear();
        editar();
        jTableusuarios.setEnabled(false);
        jBTsenha.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jBTnovoActionPerformed

    private void jBTpesquisar_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTpesquisar_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBTpesquisar_idActionPerformed

    private void jTableusuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableusuariosMouseClicked

        if(jBTsalvar.isEnabled()== false){
            jTFid.setText(String.valueOf(jTableusuarios.getModel().getValueAt(jTableusuarios.getSelectedRow(), 0)));
            jTFnome.setText(String.valueOf(jTableusuarios.getModel().getValueAt(jTableusuarios.getSelectedRow(), 1)));
            jTFsobrenome.setText(String.valueOf(jTableusuarios.getModel().getValueAt(jTableusuarios.getSelectedRow(), 2)));
            jTFtelefone.setText(String.valueOf(jTableusuarios.getModel().getValueAt(jTableusuarios.getSelectedRow(), 3)));
            jTFramal.setText(String.valueOf(jTableusuarios.getModel().getValueAt(jTableusuarios.getSelectedRow(), 4)));
            jTFemail.setText(String.valueOf(jTableusuarios.getModel().getValueAt(jTableusuarios.getSelectedRow(), 5)));
            jCBstatus.setSelectedItem(String.valueOf(jTableusuarios.getModel().getValueAt(jTableusuarios.getSelectedRow(), 6)));
            jCBperfil.setSelectedItem(String.valueOf(jTableusuarios.getModel().getValueAt(jTableusuarios.getSelectedRow(), 7)));
            jCBdepartamento.setSelectedItem(String.valueOf(jTableusuarios.getModel().getValueAt(jTableusuarios.getSelectedRow(), 8)));
            /*jBTeditar.setEnabled(true);
            jBTcancelar.setEnabled(true);
            jBTnovo.setEnabled(false);
            jTableusuarios.setEnabled(true);*/
            enableselect();
        }else{
            jTableusuarios.setEnabled(false);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jTableusuariosMouseClicked

    private void jBTsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTsalvarActionPerformed
        DAOperfil daoperf = new DAOperfil();
        Perfil pf = new Perfil();
        pf = daoperf.consultarNomePerfil(String.valueOf(jCBperfil.getSelectedItem()));
        DAOdepartamento daodepto = new DAOdepartamento();
        Departamento depto = new Departamento();
        depto = daodepto.consultarNomeDepartamento((String) jCBdepartamento.getSelectedItem());
        
        if(jCBstatus.getSelectedItem() == "Ativo"){
            usu.setStatus(true);
        }else{
            usu.setStatus(false);
        }
        if(jTFid.getText().isEmpty()){
            // É um novo usuário.
            String pass = convertPasswordToMD5(jTFemail.getText());
            usu.setNome(jTFnome.getText());
            usu.setSobreNome(jTFsobrenome.getText());
            usu.setTelefone(jTFtelefone.getText());
            usu.setRamal(jTFramal.getText());
            usu.setEmail(jTFemail.getText());
            usu.setSenha(pass);
            usu.setPerfil((String) jCBperfil.getSelectedItem());
            usu.setDepartamento((String) jCBdepartamento.getSelectedItem());
            usu.setPerfil_perf_id(pf.getId());
            usu.setDepartamento_dep_id(depto.getId());
            daousu.adicionarUsuario(usu);
            cancelar();
            enableselect();
            JOptionPane.showMessageDialog(null, "Usuário Cadastrado com sucesso");
            carregaUsuarios();
        }else{
            // É uma edição de usuário existente.
            usu.setId(Integer.parseInt(jTFid.getText()));
            usu.setNome(jTFnome.getText());
            usu.setSobreNome(jTFsobrenome.getText());
            usu.setTelefone(jTFtelefone.getText());
            usu.setRamal(jTFramal.getText());
            usu.setEmail(jTFemail.getText());
            usu.setPerfil((String) jCBperfil.getSelectedItem());
            usu.setDepartamento((String) jCBdepartamento.getSelectedItem());
            
            daousu.updateUsuario(usu);
            cancelar(); enableselect();
            JOptionPane.showMessageDialog(null, "Usuário atualizado com sucesso");
            carregaUsuarios();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jBTsalvarActionPerformed

    private void jBTsenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTsenhaActionPerformed
        String email = String.valueOf(jTFemail.getText());
        String pass = convertPasswordToMD5(email);
        DAOusuarios daouser = new DAOusuarios();
        int ret = -1;
        ret = daouser.updatePassword(pass, Integer.parseInt(jTFid.getText()));
        if(ret == 1){
            JOptionPane.showMessageDialog(rootPane, "Senha alterada com sucesso! \n A nova senha é igual ao email do usuário.");
        }else{
            JOptionPane.showMessageDialog(rootPane, "Falha ao alterar a senha!");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jBTsenhaActionPerformed

    private void jBTexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTexcluirActionPerformed
        String msg = "Tem certeza que deseja excluir o usuário "+jTFnome.getText()+" "+jTFsobrenome.getText()+" ?";
        int result = JOptionPane.showConfirmDialog(null, msg, "Confirmação de Exclusão", JOptionPane.YES_NO_OPTION);
        if(result == JOptionPane.YES_OPTION){
            daousu.excluirUsuario(Integer.parseInt(jTFid.getText()));
            carregaUsuarios();
            JOptionPane.showMessageDialog(null, "Usuário Excluido com sucesso!");  
        }else{
            JOptionPane.showMessageDialog(null, "Ação cancelada!");
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jBTexcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadUsuario().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBTcancelar;
    private javax.swing.JButton jBTeditar;
    private javax.swing.JButton jBTexcluir;
    private javax.swing.JButton jBTnovo;
    private javax.swing.JButton jBTpesquisar_email;
    private javax.swing.JButton jBTpesquisar_id;
    private javax.swing.JButton jBTsalvar;
    private javax.swing.JButton jBTsenha;
    private javax.swing.JComboBox<String> jCBdepartamento;
    private javax.swing.JComboBox<String> jCBperfil;
    private javax.swing.JComboBox<String> jCBstatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLnome;
    private javax.swing.JLabel jLnome1;
    private javax.swing.JLabel jLnome2;
    private javax.swing.JLabel jLnome3;
    private javax.swing.JLabel jLnome4;
    private javax.swing.JLabel jLnome6;
    private javax.swing.JLabel jLnome7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFemail;
    private javax.swing.JTextField jTFid;
    private javax.swing.JTextField jTFnome;
    private javax.swing.JTextField jTFramal;
    private javax.swing.JTextField jTFsobrenome;
    private javax.swing.JTextField jTFtelefone;
    private javax.swing.JTable jTableusuarios;
    // End of variables declaration//GEN-END:variables

    public void carregaUsuarios(){
      List<Usuarios> listausu = new ArrayList(); 
      listausu = daousu.listaUsuarios();
      
      DefaultTableModel model = (DefaultTableModel)jTableusuarios.getModel();
      model.setNumRows(0);
      
      for(int i=0; i < listausu.size(); i++){
          usulist = new Usuarios();
          usulist = listausu.get(i);
          String stat;
          if(usulist.isStatus() == true){
              stat = "Ativo";
          }else{
              stat= "Inativo";
          }
          model.addRow(new Object[] {usulist.getId(), usulist.getNome(), usulist.getSobreNome(), 
              usulist.getTelefone(), usulist.getRamal(), usulist.getEmail(), stat, 
              usulist.getPerfil(), usulist.getDepartamento()});
      }
      
     
      
    }
    
    public void carregaPerfil(){
        DAOperfil daoperf = new DAOperfil();
        List<Perfil> listperf;
        listperf = daoperf.listaPerfil();
        Perfil perf;
        for (int i=0; i < listperf.size(); i++){
            perf = listperf.get(i);
            jCBperfil.addItem(perf.getPerfil());
        }
      }

    public void carregaDepartamento(){
        DAOdepartamento daodepto = new DAOdepartamento();
        List<Departamento> listdepto;
        listdepto = daodepto.listaDepartamento();
        Departamento depto;
        for (int i=0; i < listdepto.size(); i++){
            depto = listdepto.get(i);
            jCBdepartamento.addItem(depto.getNome());
        }
      }

    public void enableselect(){
        jBTeditar.setEnabled(true);
        jBTcancelar.setEnabled(true);
        jBTnovo.setEnabled(false);
        jTableusuarios.setEnabled(true);
        jBTsenha.setEnabled(true);
    }
    
    public void clear(){
        jTFid.setText(null);
        jTFnome.setText(null);
        jTFsobrenome.setText(null);
        jTFtelefone.setText(null);
        jTFramal.setText(null);
        jTFemail.setText(null);
        jCBperfil.setSelectedIndex(0);
        jCBdepartamento.setSelectedIndex(0);
        jCBstatus.setSelectedIndex(0);
    }

    public void editar(){
        jTFid.setEnabled(false);
        jTFnome.setEnabled(true);
        jTFsobrenome.setEnabled(true);
        jTFtelefone.setEnabled(true);
        jTFramal.setEnabled(true);
        jTFemail.setEnabled(true);
        jCBperfil.setEnabled(true);
        jCBdepartamento.setEnabled(true);
        jCBstatus.setEnabled(true);
        jBTnovo.setEnabled(false);
        jBTeditar.setEnabled(false);
        jBTsalvar.setEnabled(true);
        jBTexcluir.setEnabled(true);
        jBTcancelar.setEnabled(true);
        jTableusuarios.setEnabled(false);
        jBTsenha.setEnabled(true);
        
    }
    
    public void cancelar(){
        jTFid.setEnabled(false);
        jTFnome.setEnabled(false);
        jTFsobrenome.setEnabled(false);
        jTFtelefone.setEnabled(false);
        jTFramal.setEnabled(false);
        jTFemail.setEnabled(false);
        jCBperfil.setEnabled(false);
        jCBdepartamento.setEnabled(false);
        jCBstatus.setEnabled(false);
        jBTnovo.setEnabled(true);
        jBTeditar.setEnabled(false);
        jBTsalvar.setEnabled(false);
        jBTexcluir.setEnabled(false);
        jBTcancelar.setEnabled(false);
        jTableusuarios.setEnabled(true);
        jBTsenha.setVisible(true);
    }

    public static String convertPasswordToMD5(String password) {
        String pass;
        MessageDigest md = null;
        try {
            md = MessageDigest.getInstance("MD5");
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
 
        BigInteger hash = new BigInteger(1, md.digest(password.getBytes()));
 
        pass = String.format("%32x", hash);
        
        System.out.println("Password Agora é : "+pass);
        return pass;
    }
    
}
