/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.DAOatendimentos;
import DAO.DAOocorrencia;
import Model.Atendimentos;
import Model.Ocorrencia;
import Model.Sessao;
import Model.Usuarios;
import java.sql.Timestamp;
import javax.swing.JOptionPane;

/**
 *
 * @author Colin
 */
public class EncerrarOco extends javax.swing.JFrame {

    /**
     * Creates new form EncerrarOco
     */
    int idoco;

    public EncerrarOco() {
        initComponents();
    }

    public EncerrarOco(int idoco) {
        initComponents();
        this.idoco = idoco;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTPdescricao = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jBTcancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Encerrar Ocorrencia");
        setResizable(false);

        jScrollPane1.setViewportView(jTPdescricao);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Descrição do atendimento:");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Confirmar");
        jButton1.setMinimumSize(new java.awt.Dimension(90, 30));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jBTcancelar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jBTcancelar.setText("Cancelar");
        jBTcancelar.setMinimumSize(new java.awt.Dimension(90, 30));
        jBTcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTcancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBTcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBTcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(531, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Usuarios usersessao;
        usersessao = Sessao.getInstance().getUsersessao();
        DAOatendimentos daoatd = new DAOatendimentos();
        Atendimentos atd = new Atendimentos();
        DAOocorrencia daooco = new DAOocorrencia();
        Ocorrencia oco = new Ocorrencia();
        Ocorrencia ocoret = new Ocorrencia();

        String msg = jTPdescricao.getText();
        try {
            //int id = Integer.parseInt(jTFidoco.getText());
            System.out.println("Mensagem = " + msg);
            //Gera data em Timestamp
            java.util.Date dtm = new java.util.Date();
            Timestamp datetm = new java.sql.Timestamp(dtm.getTime());

            System.out.println("date = " + datetm);
            atd.setData_atendimento(datetm);
            atd.setDescricao(msg);
            atd.setUsusarios_usu_id(usersessao.getId());
            atd.setOcorrencia_oco_id(idoco);
            daoatd.adicionarAtendimento(atd);

            //int idoc;
            int iduser;
            //System.out.println("id da ocorrencia: "+jTFidoco.getText());
            //idoc = Integer.parseInt(jTFidoco.getText());
            iduser = usersessao.getId();
            ocoret = daooco.updateStatus(idoco, 5, iduser, datetm);
        } catch (Exception e) {
        }

        try {
            Atendimentos atds = new Atendimentos();
            //Gera data em Timestamp
            java.util.Date dtm = new java.util.Date();
            Timestamp datetm = new java.sql.Timestamp(dtm.getTime());

            atds.setData_atendimento(datetm);
            atds.setDescricao("Atendimento Finalizado");
            atds.setUsusarios_usu_id(usersessao.getId());
            atds.setOcorrencia_oco_id(idoco);
            daoatd.adicionarAtendimento(atds);
            JOptionPane.showMessageDialog(rootPane, "Ocorrência Finalizada com Sucesso!");

            ocoret = daooco.consultarOcorrencia(idoco);
            CadOcorrencia cadoco = new CadOcorrencia(ocoret);
            cadoco.setVisible(true);

            dispose();

        } catch (Exception e) {
            System.out.println("Erro " + e);
            JOptionPane.showMessageDialog(rootPane, "Falha ao Finalizadar Ocorrência!");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jBTcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTcancelarActionPerformed
        DAOocorrencia daooco = new DAOocorrencia();
        Ocorrencia ocoret = new Ocorrencia();
        ocoret = daooco.consultarOcorrencia(idoco);
        CadOcorrencia cadoco = new CadOcorrencia(ocoret);
        cadoco.setVisible(true);
        dispose();

// TODO add your handling code here:
    }//GEN-LAST:event_jBTcancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EncerrarOco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EncerrarOco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EncerrarOco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EncerrarOco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EncerrarOco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBTcancelar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTPdescricao;
    // End of variables declaration//GEN-END:variables
}
