/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.DAOocorrencia;
import Model.Ocorrencia;
import Model.Sessao;
import Model.Usuarios;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Colin
 */
public class Principal extends javax.swing.JFrame {
    
    /**
     * Creates new form Principal
     */
    Usuarios usersessao;
    public Principal() {
        initComponents();
        
        usersessao = Sessao.getInstance().getUsersessao();
        /** habilita barra de rolagem quando necessário */
        if(usersessao.getPerfil_perf_id() == 1 || usersessao.getPerfil_perf_id() == 2){
           jPanel3.setVisible(true);
           jLusuario.setText(usersessao.getEmail());
           jLperfil.setText(usersessao.getPerfil());
        }else{
           jTPabas.remove(jPanel3);
           
           
           jBTrelatorios.setEnabled(false);
           jMenuCadastro.setEnabled(false);
           jMenuLocacao.setEnabled(false);
           jLusuario.setText(usersessao.getEmail());
           jLperfil.setText(usersessao.getPerfil());
        }
        jTBocorrencias.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        
        /** habilita a ordenação por colunas */
        jTBocorrencias.setRowSorter(new TableRowSorter());
        jTBocorrencias.setAutoCreateRowSorter(true);
        
        jTBocofinal.setRowSorter(new TableRowSorter());
        jTBocofinal.setAutoCreateRowSorter(true);
        
        jTBocoabertas.setRowSorter(new TableRowSorter());
        jTBocoabertas.setAutoCreateRowSorter(true);
        
        carregaOcorrencias();
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BGroupMinhasOco = new javax.swing.ButtonGroup();
        BGroupAguardandoAtend = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        jBTnovo = new javax.swing.JButton();
        jBTpesquisar = new javax.swing.JButton();
        jBTqualificar = new javax.swing.JButton();
        jBTrelatorios = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jTPabas = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanelfiltros = new javax.swing.JPanel();
        jRBtodos = new javax.swing.JRadioButton();
        jRBaguard = new javax.swing.JRadioButton();
        jRBatend = new javax.swing.JRadioButton();
        jRBret = new javax.swing.JRadioButton();
        jPaneltaboco = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTBocorrencias = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTBocofinal = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTBocoabertas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLusuario = new javax.swing.JLabel();
        jLperfil = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArquivo = new javax.swing.JMenu();
        jMItemSair = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuCadastro = new javax.swing.JMenu();
        jMItemCadUsuarios = new javax.swing.JMenuItem();
        jMItemCadDepartamento = new javax.swing.JMenuItem();
        jMItemCadPerfil = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMItemCadProblemas = new javax.swing.JMenuItem();
        jMItemCadCatProblemas = new javax.swing.JMenuItem();
        jMItemCadStatus = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMItemCadAtivo = new javax.swing.JMenuItem();
        jMItemCadFornecedor = new javax.swing.JMenuItem();
        jMenuLocacao = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jBTnovo.setForeground(new java.awt.Color(51, 51, 51));
        jBTnovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Help2 64.jpg"))); // NOI18N
        jBTnovo.setText("Novo");
        jBTnovo.setToolTipText("Abrir novo chamado");
        jBTnovo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(240, 240, 240), null, null));
        jBTnovo.setFocusable(false);
        jBTnovo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBTnovo.setMargin(new java.awt.Insets(2, 10, 2, 10));
        jBTnovo.setMaximumSize(new java.awt.Dimension(70, 90));
        jBTnovo.setMinimumSize(new java.awt.Dimension(70, 90));
        jBTnovo.setPreferredSize(new java.awt.Dimension(70, 90));
        jBTnovo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jBTnovo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBTnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTnovoActionPerformed(evt);
            }
        });
        jToolBar1.add(jBTnovo);

        jBTpesquisar.setForeground(new java.awt.Color(51, 51, 51));
        jBTpesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/search2 64.jpg"))); // NOI18N
        jBTpesquisar.setText("Pesquisar");
        jBTpesquisar.setToolTipText("Pesquisar Meus Chamados");
        jBTpesquisar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(240, 240, 240), null, null));
        jBTpesquisar.setEnabled(false);
        jBTpesquisar.setFocusable(false);
        jBTpesquisar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBTpesquisar.setMargin(new java.awt.Insets(2, 5, 2, 5));
        jBTpesquisar.setMaximumSize(new java.awt.Dimension(70, 90));
        jBTpesquisar.setMinimumSize(new java.awt.Dimension(70, 90));
        jBTpesquisar.setPreferredSize(new java.awt.Dimension(70, 90));
        jBTpesquisar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jBTpesquisar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jBTpesquisar);

        jBTqualificar.setForeground(new java.awt.Color(51, 51, 51));
        jBTqualificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/qualificar 4 64_1.jpg"))); // NOI18N
        jBTqualificar.setText("Qualificar");
        jBTqualificar.setToolTipText("Qualificar Chamados finalizados");
        jBTqualificar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(240, 240, 240), null, null));
        jBTqualificar.setEnabled(false);
        jBTqualificar.setFocusable(false);
        jBTqualificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBTqualificar.setMargin(new java.awt.Insets(2, 5, 2, 5));
        jBTqualificar.setMaximumSize(new java.awt.Dimension(70, 90));
        jBTqualificar.setMinimumSize(new java.awt.Dimension(70, 90));
        jBTqualificar.setPreferredSize(new java.awt.Dimension(70, 90));
        jBTqualificar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jBTqualificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jBTqualificar);

        jBTrelatorios.setForeground(new java.awt.Color(51, 51, 51));
        jBTrelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/relatorio2 64.jpg"))); // NOI18N
        jBTrelatorios.setText("Relatórios");
        jBTrelatorios.setToolTipText("Consultar Relatórios");
        jBTrelatorios.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(240, 240, 240), null, null));
        jBTrelatorios.setEnabled(false);
        jBTrelatorios.setFocusable(false);
        jBTrelatorios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBTrelatorios.setMargin(new java.awt.Insets(2, 5, 2, 5));
        jBTrelatorios.setMaximumSize(new java.awt.Dimension(70, 90));
        jBTrelatorios.setMinimumSize(new java.awt.Dimension(70, 90));
        jBTrelatorios.setPreferredSize(new java.awt.Dimension(70, 90));
        jBTrelatorios.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jBTrelatorios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jBTrelatorios);

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 204));

        jTPabas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTPabas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTPabasStateChanged(evt);
            }
        });
        jTPabas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTPabasFocusGained(evt);
            }
        });

        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jPanelfiltros.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Filtros"));
        jPanelfiltros.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanelfiltros.setPreferredSize(new java.awt.Dimension(1015, 50));

        BGroupMinhasOco.add(jRBtodos);
        jRBtodos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRBtodos.setSelected(true);
        jRBtodos.setText("Todos Chamados");
        jRBtodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBtodosActionPerformed(evt);
            }
        });

        BGroupMinhasOco.add(jRBaguard);
        jRBaguard.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRBaguard.setText("Aguardando atendimento");
        jRBaguard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBaguardActionPerformed(evt);
            }
        });

        BGroupMinhasOco.add(jRBatend);
        jRBatend.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRBatend.setText("Em atendimento");
        jRBatend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBatendActionPerformed(evt);
            }
        });

        BGroupMinhasOco.add(jRBret);
        jRBret.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRBret.setText("Aguardando retorno");
        jRBret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBretActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelfiltrosLayout = new javax.swing.GroupLayout(jPanelfiltros);
        jPanelfiltros.setLayout(jPanelfiltrosLayout);
        jPanelfiltrosLayout.setHorizontalGroup(
            jPanelfiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelfiltrosLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jRBtodos)
                .addGap(32, 32, 32)
                .addComponent(jRBaguard)
                .addGap(28, 28, 28)
                .addComponent(jRBatend)
                .addGap(18, 18, 18)
                .addComponent(jRBret)
                .addContainerGap(309, Short.MAX_VALUE))
        );
        jPanelfiltrosLayout.setVerticalGroup(
            jPanelfiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelfiltrosLayout.createSequentialGroup()
                .addGroup(jPanelfiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBtodos)
                    .addComponent(jRBaguard)
                    .addComponent(jRBatend)
                    .addComponent(jRBret))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPaneltaboco.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPaneltaboco.setAutoscrolls(true);
        jPaneltaboco.setPreferredSize(new java.awt.Dimension(1000, 385));

        jTBocorrencias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "DATA ABERTURA", "STATUS", "USUÁRIO", "ID EQUIPTO", "CAT. PROBLEMA", "PROBLEMA", "DESCRIÇÃO", "DATA FECHAMENTO"
            }
        ));
        jTBocorrencias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTBocorrenciasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTBocorrencias);
        if (jTBocorrencias.getColumnModel().getColumnCount() > 0) {
            jTBocorrencias.getColumnModel().getColumn(0).setMinWidth(30);
            jTBocorrencias.getColumnModel().getColumn(1).setMinWidth(100);
            jTBocorrencias.getColumnModel().getColumn(2).setMinWidth(150);
            jTBocorrencias.getColumnModel().getColumn(3).setMinWidth(100);
            jTBocorrencias.getColumnModel().getColumn(4).setMinWidth(80);
            jTBocorrencias.getColumnModel().getColumn(5).setMinWidth(100);
            jTBocorrencias.getColumnModel().getColumn(6).setMinWidth(80);
            jTBocorrencias.getColumnModel().getColumn(7).setMinWidth(400);
            jTBocorrencias.getColumnModel().getColumn(8).setMinWidth(80);
        }

        javax.swing.GroupLayout jPaneltabocoLayout = new javax.swing.GroupLayout(jPaneltaboco);
        jPaneltaboco.setLayout(jPaneltabocoLayout);
        jPaneltabocoLayout.setHorizontalGroup(
            jPaneltabocoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneltabocoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPaneltabocoLayout.setVerticalGroup(
            jPaneltabocoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneltabocoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelfiltros, javax.swing.GroupLayout.DEFAULT_SIZE, 999, Short.MAX_VALUE)
                    .addComponent(jPaneltaboco, javax.swing.GroupLayout.DEFAULT_SIZE, 999, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanelfiltros, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPaneltaboco, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE))
        );

        jTPabas.addTab("Minhas Ocorrências", null, jPanel1, "");

        jPanel2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel2FocusGained(evt);
            }
        });

        jTBocofinal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "DATA ABERTURA", "STATUS", "USUÁRIO", "ID EQUIPTO", "CAT. PROBLEMA", "PROBLEMA", "DESCRIÇÃO", "DATA FECHAMENTO"
            }
        ));
        jTBocofinal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTBocofinalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTBocofinalMouseEntered(evt);
            }
        });
        jScrollPane3.setViewportView(jTBocofinal);
        if (jTBocofinal.getColumnModel().getColumnCount() > 0) {
            jTBocofinal.getColumnModel().getColumn(0).setMinWidth(30);
            jTBocofinal.getColumnModel().getColumn(1).setMinWidth(80);
            jTBocofinal.getColumnModel().getColumn(2).setMinWidth(80);
            jTBocofinal.getColumnModel().getColumn(3).setMinWidth(100);
            jTBocofinal.getColumnModel().getColumn(4).setMinWidth(80);
            jTBocofinal.getColumnModel().getColumn(5).setMinWidth(100);
            jTBocofinal.getColumnModel().getColumn(6).setMinWidth(80);
            jTBocofinal.getColumnModel().getColumn(7).setMinWidth(400);
            jTBocofinal.getColumnModel().getColumn(8).setMinWidth(80);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );

        jTPabas.addTab("Ocorrências Finalizadas", null, jPanel2, "");

        jPanel3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel3FocusGained(evt);
            }
        });

        jTBocoabertas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "DATA ABERTURA", "STATUS", "USUÁRIO", "ID EQUIPTO", "CAT. PROBLEMA", "PROBLEMA", "DESCRIÇÃO", "DATA FECHAMENTO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTBocoabertas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTBocoabertasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTBocoabertasMouseEntered(evt);
            }
        });
        jScrollPane4.setViewportView(jTBocoabertas);
        if (jTBocoabertas.getColumnModel().getColumnCount() > 0) {
            jTBocoabertas.getColumnModel().getColumn(0).setMinWidth(30);
            jTBocoabertas.getColumnModel().getColumn(1).setMinWidth(100);
            jTBocoabertas.getColumnModel().getColumn(2).setMinWidth(150);
            jTBocoabertas.getColumnModel().getColumn(3).setMinWidth(100);
            jTBocoabertas.getColumnModel().getColumn(4).setMinWidth(80);
            jTBocoabertas.getColumnModel().getColumn(5).setMinWidth(100);
            jTBocoabertas.getColumnModel().getColumn(6).setMinWidth(80);
            jTBocoabertas.getColumnModel().getColumn(7).setMinWidth(400);
            jTBocoabertas.getColumnModel().getColumn(8).setMinWidth(80);
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 999, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTPabas.addTab("Aguardando atendimento", jPanel3);

        jDesktopPane1.setLayer(jTPabas, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTPabas, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTPabas)
        );

        jTPabas.getAccessibleContext().setAccessibleName("Finalizados");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Usuário:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Perfil:");

        jLusuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLusuario.setForeground(new java.awt.Color(255, 51, 0));
        jLusuario.setText("d");
        jLusuario.setOpaque(true);

        jLperfil.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLperfil.setForeground(new java.awt.Color(255, 51, 0));
        jLperfil.setText("d");
        jLperfil.setOpaque(true);

        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jMenuArquivo.setText("Arquivo");

        jMItemSair.setText("Sair");
        jMItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMItemSairActionPerformed(evt);
            }
        });
        jMenuArquivo.add(jMItemSair);

        jMenuItem1.setText("Alterar Senha");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuArquivo.add(jMenuItem1);

        jMenuItem3.setText("Logof");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenuArquivo.add(jMenuItem3);

        jMenuBar1.add(jMenuArquivo);

        jMenuCadastro.setText("Cadastro");

        jMItemCadUsuarios.setText("Usuários");
        jMItemCadUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMItemCadUsuariosActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMItemCadUsuarios);

        jMItemCadDepartamento.setText("Departamento");
        jMItemCadDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMItemCadDepartamentoActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMItemCadDepartamento);

        jMItemCadPerfil.setText("Perfil");
        jMItemCadPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMItemCadPerfilActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMItemCadPerfil);
        jMenuCadastro.add(jSeparator1);

        jMItemCadProblemas.setText("Problemas");
        jMItemCadProblemas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMItemCadProblemasActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMItemCadProblemas);

        jMItemCadCatProblemas.setText("Categoria de Problemas");
        jMItemCadCatProblemas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMItemCadCatProblemasActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMItemCadCatProblemas);

        jMItemCadStatus.setText("Status de Ocorrencia");
        jMItemCadStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMItemCadStatusActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMItemCadStatus);
        jMenuCadastro.add(jSeparator2);

        jMItemCadAtivo.setText("Ativo");
        jMItemCadAtivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMItemCadAtivoActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMItemCadAtivo);

        jMItemCadFornecedor.setText("Fornecedor");
        jMItemCadFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMItemCadFornecedorActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMItemCadFornecedor);

        jMenuBar1.add(jMenuCadastro);

        jMenuLocacao.setText("Locação");

        jMenuItem2.setText("Locação de Ativos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuLocacao.add(jMenuItem2);

        jMenuBar1.add(jMenuLocacao);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLperfil, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(jLusuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLusuario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLperfil))))
                .addGap(10, 10, 10)
                .addComponent(jDesktopPane1))
        );

        setSize(new java.awt.Dimension(1040, 634));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMItemCadCatProblemasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMItemCadCatProblemasActionPerformed
        CadCatProblemas CadCatProb = new CadCatProblemas();
        CadCatProb.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMItemCadCatProblemasActionPerformed

    private void jMItemCadFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMItemCadFornecedorActionPerformed
        CadFornecedor CadForn = new CadFornecedor();
        CadForn.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMItemCadFornecedorActionPerformed

    private void jMItemCadUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMItemCadUsuariosActionPerformed
        CadUsuario CadUser = new CadUsuario();
        CadUser.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMItemCadUsuariosActionPerformed

    private void jMItemCadDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMItemCadDepartamentoActionPerformed
        CadDepartamento CadDep = new CadDepartamento();
        CadDep.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMItemCadDepartamentoActionPerformed

    private void jMItemCadPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMItemCadPerfilActionPerformed
            CadPerfil CadPerf = new CadPerfil();
            CadPerf.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jMItemCadPerfilActionPerformed

    private void jMItemCadProblemasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMItemCadProblemasActionPerformed
        CadProblemas CadProb = new CadProblemas();
        CadProb.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMItemCadProblemasActionPerformed

    private void jMItemCadStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMItemCadStatusActionPerformed
        CadStatus CadStat = new CadStatus();
        CadStat.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMItemCadStatusActionPerformed

    private void jMItemCadAtivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMItemCadAtivoActionPerformed
        CadAtivos CadAtv = new CadAtivos();
        CadAtv.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMItemCadAtivoActionPerformed

    private void jMItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMItemSairActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMItemSairActionPerformed

    private void jBTnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTnovoActionPerformed
        CadOcorrencia novaoco = new CadOcorrencia();
        novaoco.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jBTnovoActionPerformed

    private void jTBocorrenciasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTBocorrenciasMouseClicked
        
        System.out.println("\n ------ MouseClicked jTableocorrencia: "+jTPabas.getSelectedIndex());
        exibeOcorrencia();

    }//GEN-LAST:event_jTBocorrenciasMouseClicked

    private void jRBretActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBretActionPerformed
        carregaOcorrencias();
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBretActionPerformed

    private void jRBatendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBatendActionPerformed
        carregaOcorrencias();
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBatendActionPerformed

    private void jRBaguardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBaguardActionPerformed
        carregaOcorrencias();
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBaguardActionPerformed

    private void jRBtodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBtodosActionPerformed
        carregaOcorrencias();
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBtodosActionPerformed

    private void jTBocofinalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTBocofinalMouseClicked
        System.out.println("\n ------ MouseClicked jTableocofinal: "+jTPabas.getSelectedIndex());
        int id = (int) jTBocofinal.getModel().getValueAt(jTBocofinal.getSelectedRow(), 0);
        exibeOcorrencia(id);
        // TODO add your handling code here:
    }//GEN-LAST:event_jTBocofinalMouseClicked

    private void jTPabasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTPabasFocusGained
        System.out.println("\n ------ jTPabasFocusGained: "+jTPabas.getSelectedIndex());
        carregaOcorrencias();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jTPabasFocusGained

    private void jTBocoabertasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTBocoabertasMouseClicked
        
        int id = (int) jTBocoabertas.getModel().getValueAt(jTBocoabertas.getSelectedRow(), 0);
        
        exibeOcorrencia(id);
        // TODO add your handling code here:
    }//GEN-LAST:event_jTBocoabertasMouseClicked

    private void jPanel3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel3FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3FocusGained

    private void jPanel2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel2FocusGained
        carregaOcorrencias();
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2FocusGained

    private void jTPabasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTPabasStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jTPabasStateChanged

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        AlterarSenha AS = new AlterarSenha();
        this.jDesktopPane1.add(AS);
        AS.setVisible(true);
        AS.moveToFront();
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jTBocofinalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTBocofinalMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTBocofinalMouseEntered

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        cadLocacaoAtivos locacao = new cadLocacaoAtivos();
        locacao.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jTBocoabertasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTBocoabertasMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTBocoabertasMouseEntered

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        dispose();
        Login login = new Login();
        login.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BGroupAguardandoAtend;
    private javax.swing.ButtonGroup BGroupMinhasOco;
    private javax.swing.JButton jBTnovo;
    private javax.swing.JButton jBTpesquisar;
    private javax.swing.JButton jBTqualificar;
    private javax.swing.JButton jBTrelatorios;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLperfil;
    private javax.swing.JLabel jLusuario;
    private javax.swing.JMenuItem jMItemCadAtivo;
    private javax.swing.JMenuItem jMItemCadCatProblemas;
    private javax.swing.JMenuItem jMItemCadDepartamento;
    private javax.swing.JMenuItem jMItemCadFornecedor;
    private javax.swing.JMenuItem jMItemCadPerfil;
    private javax.swing.JMenuItem jMItemCadProblemas;
    private javax.swing.JMenuItem jMItemCadStatus;
    private javax.swing.JMenuItem jMItemCadUsuarios;
    private javax.swing.JMenuItem jMItemSair;
    private javax.swing.JMenu jMenuArquivo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenu jMenuLocacao;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelfiltros;
    private javax.swing.JPanel jPaneltaboco;
    private javax.swing.JRadioButton jRBaguard;
    private javax.swing.JRadioButton jRBatend;
    private javax.swing.JRadioButton jRBret;
    private javax.swing.JRadioButton jRBtodos;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTable jTBocoabertas;
    private javax.swing.JTable jTBocofinal;
    private javax.swing.JTable jTBocorrencias;
    private javax.swing.JTabbedPane jTPabas;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
    
   public void carregaOcorrencias(){
       System.out.println("\n ------carregaOcorrencias -------------------");
       
       DAOocorrencia daooco = new DAOocorrencia();
       List<Ocorrencia> listoco = new ArrayList();
       Ocorrencia oco;
       DefaultTableModel model = (DefaultTableModel) jTBocorrencias.getModel();
       model.setNumRows(0);
       DefaultTableModel modelfinal = (DefaultTableModel) jTBocofinal.getModel();
       modelfinal.setNumRows(0);
       DefaultTableModel modelocoabertas = (DefaultTableModel) jTBocoabertas.getModel();
       modelocoabertas.setNumRows(0);
       
       //Lista ocorrencias de acordo com o filtro selecionado
       if(jRBtodos.isSelected() && jTPabas.getSelectedIndex()==0){ // todas as ocorrencias
           listoco = daooco.listaOcorrencia(usersessao.getId());
           for(int i=0; i<listoco.size(); i++){
               oco = listoco.get(i);
               model.addRow(new Object[]{oco.getId(), oco.getDataabertura(), oco.getStatus(), 
                   oco.getUsuario(), oco.getAtivos_atv_id(), oco.getCatproblema(), oco.getProblema(), 
                   oco.getDescricao(), oco.getDatafechamento()});
           }
       }
       else if(jRBaguard.isSelected() && jTPabas.getSelectedIndex()==0){ // Somente ocorrencias aguardando atendimento
           listoco = daooco.listaOcorrencia(usersessao.getId(), 1);
           for(int i=0; i<listoco.size(); i++){
               oco = listoco.get(i);
               model.addRow(new Object[]{oco.getId(), oco.getDataabertura(), oco.getStatus(), 
                   oco.getUsuario(), oco.getAtivos_atv_id(), oco.getCatproblema(), oco.getProblema(), 
                   oco.getDescricao(), oco.getDatafechamento()});
           }
       }
       else if(jRBatend.isSelected() && jTPabas.getSelectedIndex()==0){ //Somente ocorrencias em atendimento
           listoco = daooco.listaOcorrencia(usersessao.getId(), 2);
           for(int i=0; i<listoco.size(); i++){
               oco = listoco.get(i);
               model.addRow(new Object[]{oco.getId(), oco.getDataabertura(), oco.getStatus(), 
                   oco.getUsuario(), oco.getAtivos_atv_id(), oco.getCatproblema(), oco.getProblema(), 
                   oco.getDescricao(), oco.getDatafechamento()});
           }           
       }
       else if(jRBret.isSelected() && jTPabas.getSelectedIndex()==0){ //Somente ocorrencias aguarndando retorno do usuário
           listoco = daooco.listaOcorrencia(usersessao.getId(), 3);
           for(int i=0; i<listoco.size(); i++){
               oco = listoco.get(i);
               model.addRow(new Object[]{oco.getId(), oco.getDataabertura(), oco.getStatus(), 
                   oco.getUsuario(), oco.getAtivos_atv_id(), oco.getCatproblema(), oco.getProblema(), 
                   oco.getDescricao(), oco.getDatafechamento()});
            }
           
        }
       else if(jTPabas.getSelectedIndex() == 1){ //Somente ocorrencias finalizadas do usuário
           System.out.println("\n ------ CarregaOcorrencias da Tab Finalizadas");
           
           listoco = daooco.listaOcorrencia(usersessao.getId(), 5);
           for(int i=0; i<listoco.size(); i++){
               oco = listoco.get(i);
               modelfinal.addRow(new Object[]{oco.getId(), oco.getDataabertura(), oco.getStatus(), 
                   oco.getUsuario(), oco.getAtivos_atv_id(), oco.getCatproblema(), oco.getProblema(), 
                   oco.getDescricao(), oco.getDatafechamento()});
            }
        }
       else if(jTPabas.getSelectedIndex() == 2){
           System.out.println("\n ------ CarregaOcorrencias da Tab Aguardando atendimento");
           
           //listoco = daooco.listaOcorrenciastatus(1);//lista todas ocorrencias que estão aguardando atendimento
           listoco = daooco.listaOcorrencia();//lista todas ocorrencias que estão aguardando atendimento
           for(int i=0; i<listoco.size(); i++){
               oco = listoco.get(i);
               modelocoabertas.addRow(new Object[]{oco.getId(), oco.getDataabertura(), oco.getStatus(), 
                   oco.getUsuario(), oco.getAtivos_atv_id(), oco.getCatproblema(), oco.getProblema(), 
                   oco.getDescricao(), oco.getDatafechamento()});
            }
        }
   }
   
   public void exibeOcorrencia(){
       System.out.println("\n ------ Principal - exibeOcorrencia ()-------");
       
        DAOocorrencia daooco = new DAOocorrencia();
        int id = (int) jTBocorrencias.getModel().getValueAt(jTBocorrencias.getSelectedRow(), 0);
        
        Ocorrencia oco = new Ocorrencia();
        oco = daooco.consultarOcorrencia(id);
        
        
        oco.setId((int) jTBocorrencias.getModel().getValueAt(jTBocorrencias.getSelectedRow(), 0));
        oco.setDataabertura((Timestamp) jTBocorrencias.getModel().getValueAt(jTBocorrencias.getSelectedRow(), 1));
        oco.setStatus((String) jTBocorrencias.getModel().getValueAt(jTBocorrencias.getSelectedRow(), 2));
        oco.setUsuario((String) jTBocorrencias.getModel().getValueAt(jTBocorrencias.getSelectedRow(), 3));
        oco.setAtivos_atv_id((int) jTBocorrencias.getModel().getValueAt(jTBocorrencias.getSelectedRow(), 4));
        oco.setCatproblema((String) jTBocorrencias.getModel().getValueAt(jTBocorrencias.getSelectedRow(), 5));
        oco.setProblema((String) jTBocorrencias.getModel().getValueAt(jTBocorrencias.getSelectedRow(), 6));
        oco.setDescricao((String) jTBocorrencias.getModel().getValueAt(jTBocorrencias.getSelectedRow(), 7));
        oco.setDatafechamento((Timestamp) jTBocorrencias.getModel().getValueAt(jTBocorrencias.getSelectedRow(), 8));
        
        CadOcorrencia cadoco = new CadOcorrencia (oco);
        cadoco.setVisible(true);
   }
   
   public void exibeOcorrencia(int idoco){
       System.out.println("\n ------ Principal - exibeOcorrencia (int idooco) -------");
       
        DAOocorrencia daooco = new DAOocorrencia();       
        Ocorrencia oco = new Ocorrencia();
        oco = daooco.consultarOcorrencia(idoco);
        
        CadOcorrencia cadoco = new CadOcorrencia (oco);
        cadoco.setVisible(true);
   }
   
}
